<?php

namespace App\Constants;

class DatabaseConstants
{
    // ID Field Names
    public const PAYER_ID = 'PayerID';
    public const APP_PAYER_ID = 'AppPayerID';
    public const PROVIDER_ID = 'ProviderID';
    public const APP_PROVIDER_ID = 'AppProviderID';
    
    // Data Field Names
    public const RESULTS = 'results';
    public const CON_TO = 'CON_TO';
    public const CO_TO = 'CO_TO';
    
    // Database Fields
    public const _SP = '_SP';
    public const _OP = '_OP';
    public const _FP = '_FP';
    public const CON_SP = 'CON_SP';
    public const CON_OP = 'CON_OP';
    public const CON_FP = 'CON_FP';
    public const PNAME = 'PNAME';
    public const PLNAME = 'PLNAME';
    public const PFNAME = 'PFNAME';
    public const TOTAL_RECORDS = 'TotalRecords';
    
    // SQL Query Parts
    public const BI_DIMUSEROFFICES_JOIN = '.BI.DIMUSEROFFICES AS DUO ON DUO."Office Id" = PDT.OFFICEID AND DUO."Vendor Id" = PDT.PROVIDERID AND DUO."User Id" = ';
    public const VENDOR_TYPE_WHERE = ' AND DUO."Vendor Type" = \'Vendor\' WHERE PDT.PROVIDERID = \'';
    public const CRDATEUNIQUE_BETWEEN = ' AND PDT.CRDATEUNIQUE BETWEEN \'';
    
    // Setup Database Operations
    public const UPDATE_CONFLICTREPORT = 'UPDATE CONFLICTREPORT';
    public const INSERT_CONFLICTREPORT = 'INSERT INTO CONFLICTREPORT';
    public const DELETE_CONFLICTREPORT = 'DELETE FROM CONFLICTREPORT';
    public const SELECT_COUNT_ID = 'SELECT COUNT(ID) AS "count" FROM CONFLICTREPORT';
    public const SELECT_COUNT_ALL = 'SELECT COUNT(*) as count FROM CONFLICTREPORT';
    public const SELECT_ALL_CONFLICTREPORT = 'SELECT * FROM CONFLICTREPORT';
    
    // Setup Database Field Names
    public const COUNT = 'count';
    public const COUNT_UPPER = 'COUNT';
    public const QUERY = 'query';
    
    // Setup SQL Error Codes
    public const SQL_INTEGRITY_CONSTRAINT_VIOLATION = '23000';
    
    // Setup Environment Variables
    public const PROVIDER_IDS = 'PROVIDERIDS';
    public const A_PROVIDER_IDS = 'APROVIDERIDS';
    
    // Dashboard Queries    
    public const QUERY_PROVIDER_CONFLICT_TYPE = 'SELECT SUM(PDT.EX_ST_MATCH_TO) AS EX_ST_MATCH_TO, SUM(PDT.EX_ST_MATCH_SP) AS EX_ST_MATCH_SP, SUM(PDT.EX_ST_MATCH_OP) AS EX_ST_MATCH_OP, SUM(PDT.EX_ST_MATCH_FP) AS EX_ST_MATCH_FP, SUM(PDT.EX_VT_MATCH_TO) AS EX_VT_MATCH_TO, SUM(PDT.EX_VT_MATCH_SP) AS EX_VT_MATCH_SP, SUM(PDT.EX_VT_MATCH_OP) AS EX_VT_MATCH_OP, SUM(PDT.EX_VT_MATCH_FP) AS EX_VT_MATCH_FP, SUM(PDT.EX_ST_VT_MATCH_TO) AS EX_ST_VT_MATCH_TO, SUM(PDT.EX_ST_VT_MATCH_SP) AS EX_ST_VT_MATCH_SP, SUM(PDT.EX_ST_VT_MATCH_OP) AS EX_ST_VT_MATCH_OP, SUM(PDT.EX_ST_VT_MATCH_FP) AS EX_ST_VT_MATCH_FP, SUM(PDT.ST_OVR_TO) AS ST_OVR_TO, SUM(PDT.ST_OVR_SP) AS ST_OVR_SP, SUM(PDT.ST_OVR_OP) AS ST_OVR_OP, SUM(PDT.ST_OVR_FP) AS ST_OVR_FP, SUM(PDT.VT_OVR_TO) AS VT_OVR_TO, SUM(PDT.VT_OVR_SP) AS VT_OVR_SP, SUM(PDT.VT_OVR_OP) AS VT_OVR_OP, SUM(PDT.VT_OVR_FP) AS VT_OVR_FP, SUM(PDT.ST_VT_OVR_TO) AS ST_VT_OVR_TO, SUM(PDT.ST_VT_OVR_SP) AS ST_VT_OVR_SP, SUM(PDT.ST_VT_OVR_OP) AS ST_VT_OVR_OP, SUM(PDT.ST_VT_OVR_FP) AS ST_VT_OVR_FP, SUM(PDT.TD_TO) AS TD_TO, SUM(PDT.TD_SP) AS TD_SP, SUM(PDT.TD_OP) AS TD_OP, SUM(PDT.TD_FP) AS TD_FP, SUM(PDT.IN_TO) AS IN_TO, SUM(PDT.IN_SP) AS IN_SP, SUM(PDT.IN_OP) AS IN_OP, SUM(PDT.IN_FP) AS IN_FP, SUM(PDT.PT_TO) AS PT_TO, SUM(PDT.PT_SP) AS PT_SP, SUM(PDT.PT_OP) AS PT_OP, SUM(PDT.PT_FP) AS PT_FP FROM CONFLICTREPORT{DB_SUFFIX}.PUBLIC.PROVIDER_DASHBOARD_CON_TYP AS PDT INNER JOIN ANALYTICS{DB_SUFFIX}.BI.DIMUSEROFFICES AS DUO ON DUO."Office Id" = PDT.OFFICEID AND DUO."Vendor Id" = PDT.PROVIDERID AND DUO."User Id" = \'{USER_ID}\' AND DUO."Vendor Type" = \'Vendor\' WHERE PDT.PROVIDERID = \'{PROVIDER_ID}\' AND PDT.CRDATEUNIQUE BETWEEN \'{START_DATE}\' AND \'{END_DATE}\'';
    
    public const QUERY_PROVIDER_AGENCY = 'SELECT TOP 10 PDT.CONPROVIDERID, PDT.CON_P_NAME, PDT.CON_TIN, SUM(PDT.CON_TO) AS CON_TO, SUM(PDT.CON_SP) AS CON_SP, SUM(PDT.CON_OP) AS CON_OP, SUM(PDT.CON_FP) AS CON_FP FROM CONFLICTREPORT{DB_SUFFIX}.PUBLIC.PROVIDER_DASHBOARD_AGENCY AS PDT INNER JOIN ANALYTICS{DB_SUFFIX}.BI.DIMUSEROFFICES AS DUO ON DUO."Office Id" = PDT.OFFICEID AND DUO."Vendor Id" = PDT.PROVIDERID AND DUO."User Id" = \'{USER_ID}\' AND DUO."Vendor Type" = \'Vendor\' WHERE PDT.PROVIDERID = \'{PROVIDER_ID}\' AND PDT.CRDATEUNIQUE BETWEEN \'{START_DATE}\' AND \'{END_DATE}\' GROUP BY PDT.CONPROVIDERID,PDT.CON_P_NAME, PDT.CON_TIN ORDER BY CON_TO DESC';
    
    public const QUERY_PROVIDER_CAREGIVER = 'SELECT TOP 10 PDT.CAREGIVERID, PDT.C_CODE, PDT.C_NAME, SUM(PDT.CON_TO) AS CON_TO, SUM(PDT.CON_SP) AS CON_SP, SUM(PDT.CON_OP) AS CON_OP, SUM(PDT.CON_FP) AS CON_FP FROM CONFLICTREPORT{DB_SUFFIX}.PUBLIC.PROVIDER_DASHBOARD_CAREGIVER AS PDT INNER JOIN ANALYTICS{DB_SUFFIX}.BI.DIMUSEROFFICES AS DUO ON DUO."Office Id" = PDT.OFFICEID AND DUO."Vendor Id" = PDT.PROVIDERID AND DUO."User Id" = \'{USER_ID}\' AND DUO."Vendor Type" = \'Vendor\' WHERE PDT.PROVIDERID = \'{PROVIDER_ID}\' AND PDT.CRDATEUNIQUE BETWEEN \'{START_DATE}\' AND \'{END_DATE}\' GROUP BY PDT.CAREGIVERID, PDT.C_CODE, PDT.C_NAME ORDER BY CON_TO DESC';
    
    public const QUERY_PROVIDER_PATIENT = 'SELECT TOP 10 PDT.PATIENTID, PDT.PFNAME, PDT.PLNAME, PDT.PNAME, SUM(PDT.CON_TO) AS CON_TO, SUM(PDT.CON_SP) AS CON_SP, SUM(PDT.CON_OP) AS CON_OP, SUM(PDT.CON_FP) AS CON_FP FROM CONFLICTREPORT{DB_SUFFIX}.PUBLIC.PROVIDER_DASHBOARD_PATIENT AS PDT INNER JOIN ANALYTICS{DB_SUFFIX}.BI.DIMUSEROFFICES AS DUO ON DUO."Office Id" = PDT.OFFICEID AND DUO."Vendor Id" = PDT.PROVIDERID AND DUO."User Id" = \'{USER_ID}\' AND DUO."Vendor Type" = \'Vendor\' WHERE PDT.PROVIDERID = \'{PROVIDER_ID}\' AND PDT.CRDATEUNIQUE BETWEEN \'{START_DATE}\' AND \'{END_DATE}\' GROUP BY PDT.PATIENTID, PDT.PFNAME, PDT.PLNAME, PDT.PNAME ORDER BY CON_TO DESC';
    
    //public const QUERY_PAYER_CONFLICT_TYPE = 'SELECT CONTYPE, CONTYPES, SUM(CO_TO) AS CO_TO, SUM(CO_SP) AS CO_SP, SUM(CO_OP) AS CO_OP, SUM(CO_FP) AS CO_FP FROM CONFLICTREPORT{DB_SUFFIX}.PUBLIC.PAYER_DASHBOARD_CON_TYP WHERE PAYERID = \'{PAYER_ID}\' AND CRDATEUNIQUE BETWEEN \'{START_DATE}\' AND \'{END_DATE}\' GROUP BY CONTYPE, CONTYPES ORDER BY CO_TO DESC';
    
    //public const QUERY_PAYER_AGENCY = 'SELECT TOP 10 PROVIDERID, P_NAME, TIN, SUM(CON_TO) AS CON_TO, SUM(CON_SP) AS CON_SP, SUM(CON_OP) AS CON_OP, SUM(CON_FP) AS CON_FP FROM CONFLICTREPORT{DB_SUFFIX}.PUBLIC.PAYER_DASHBOARD_AGENCY WHERE PAYERID = \'{PAYER_ID}\' AND CRDATEUNIQUE BETWEEN \'{START_DATE}\' AND \'{END_DATE}\' GROUP BY PROVIDERID, P_NAME, TIN ORDER BY CON_TO DESC';
    
    //public const QUERY_PAYER_CAREGIVER = 'SELECT TOP 10 CAREGIVERID, C_NAME, C_LNAME, C_FNAME, SUM(CON_TO) AS CON_TO, SUM(CON_SP) AS CON_SP, SUM(CON_OP) AS CON_OP, SUM(CON_FP) AS CON_FP FROM CONFLICTREPORT{DB_SUFFIX}.PUBLIC.PAYER_DASHBOARD_CAREGIVER WHERE PAYERID = \'{PAYER_ID}\' AND CRDATEUNIQUE BETWEEN \'{START_DATE}\' AND \'{END_DATE}\' GROUP BY CAREGIVERID, C_NAME, C_LNAME, C_FNAME ORDER BY CON_TO DESC';
    
    //public const QUERY_PAYER_PATIENT = 'SELECT TOP 10 PATIENTID, PFNAME, PLNAME, PNAME, ADMISSIONID, SUM(CON_TO) AS CON_TO, SUM(CON_SP) AS CON_SP, SUM(CON_OP) AS CON_OP, SUM(CON_FP) AS CON_FP FROM CONFLICTREPORT{DB_SUFFIX}.PUBLIC.PAYER_DASHBOARD_PATIENT WHERE PAYERID = \'{PAYER_ID}\' AND CRDATEUNIQUE BETWEEN \'{START_DATE}\' AND \'{END_DATE}\' GROUP BY PATIENTID, PFNAME, PLNAME, PNAME, ADMISSIONID ORDER BY CON_TO DESC';
    
    //public const QUERY_PAYER_PAYER = 'SELECT TOP 10 CONPAYERID, PNAME, SUM(CON_TO) AS CON_TO, SUM(CON_SP) AS CON_SP, SUM(CON_OP) AS CON_OP, SUM(CON_FP) AS CON_FP FROM CONFLICTREPORT{DB_SUFFIX}.PUBLIC.PAYER_DASHBOARD_PAYER WHERE PAYERID = \'{PAYER_ID}\' AND CONPAYERID != \'{PAYER_ID}\' AND CRDATEUNIQUE BETWEEN \'{START_DATE}\' AND \'{END_DATE}\' GROUP BY CONPAYERID, PNAME ORDER BY CON_TO DESC';
    
    public const QUERY_PROVIDER_PAYER = 'SELECT TOP 10 PDT.PAYERID, PDT.PNAME, SUM(PDT.CON_TO) AS CON_TO, SUM(PDT.CON_SP) AS CON_SP, SUM(PDT.CON_OP) AS CON_OP, SUM(PDT.CON_FP) AS CON_FP FROM CONFLICTREPORT{DB_SUFFIX}.PUBLIC.PROVIDER_DASHBOARD_PAYER AS PDT INNER JOIN ANALYTICS{DB_SUFFIX}.BI.DIMUSEROFFICES AS DUO ON DUO."Office Id" = PDT.OFFICEID AND DUO."Vendor Id" = PDT.PROVIDERID AND DUO."User Id" = \'{USER_ID}\' AND DUO."Vendor Type" = \'Vendor\' WHERE PDT.PROVIDERID = \'{PROVIDER_ID}\' AND PDT.CRDATEUNIQUE BETWEEN \'{START_DATE}\' AND \'{END_DATE}\' GROUP BY PDT.PAYERID, PDT.PNAME ORDER BY CON_TO DESC';
    
    // New Chart Table Queries for Conflict Types Only - Combined Query
    public const QUERY_PAYER_CONFLICT_TYPE = 'WITH counts_cte AS (SELECT CONTYPE, CONTYPEDESC, COUNT(DISTINCT VISIT_KEY) AS CO_TO FROM CONFLICTREPORT{DB_SUFFIX}.PUBLIC.PAYER_DASHBOARD_CON_TYP_COUNT WHERE PAYERID = \'{PAYER_ID}\' AND VISITDATE BETWEEN \'{START_DATE}\' AND \'{END_DATE}\' GROUP BY CONTYPE, CONTYPEDESC), impacts_cte AS (SELECT CONTYPE, CONTYPEDESC, SUM(CON_SP) AS CO_SP, SUM(CON_OP) AS CO_OP, SUM(CON_FP) AS CO_FP FROM CONFLICTREPORT{DB_SUFFIX}.PUBLIC.PAYER_DASHBOARD_CON_TYP_IMPACT WHERE PAYERID = \'{PAYER_ID}\' AND VISITDATE BETWEEN \'{START_DATE}\' AND \'{END_DATE}\' GROUP BY CONTYPE, CONTYPEDESC) SELECT c.CONTYPE, c.CONTYPEDESC, c.CO_TO, COALESCE(i.CO_SP, 0) AS CO_SP, COALESCE(i.CO_OP, 0) AS CO_OP, COALESCE(i.CO_FP, 0) AS CO_FP FROM counts_cte AS c LEFT JOIN impacts_cte AS i ON c.CONTYPE = i.CONTYPE AND c.CONTYPEDESC = i.CONTYPEDESC ORDER BY c.CO_TO DESC';
    
    // New Chart Table Queries for Agency Dashboard
    public const QUERY_PAYER_AGENCY_COUNT = 'WITH TopAgencyCounts AS (SELECT PROVIDERID, P_NAME, TIN, COUNT(DISTINCT VISIT_KEY) AS CON_TO FROM CONFLICTREPORT{DB_SUFFIX}.PUBLIC.PAYER_DASHBOARD_AGENCY_COUNT WHERE PAYERID = \'{PAYER_ID}\' AND VISITDATE BETWEEN \'{START_DATE}\' AND \'{END_DATE}\' GROUP BY PROVIDERID, P_NAME, TIN ORDER BY CON_TO DESC LIMIT 10), AgencyImpacts AS (SELECT PROVIDERID, P_NAME, TIN, SUM(CON_SP) AS CON_SP, SUM(CON_OP) AS CON_OP, SUM(CON_FP) AS CON_FP FROM CONFLICTREPORT{DB_SUFFIX}.PUBLIC.PAYER_DASHBOARD_AGENCY_IMPACT WHERE PAYERID = \'{PAYER_ID}\' AND VISITDATE BETWEEN \'{START_DATE}\' AND \'{END_DATE}\' GROUP BY PROVIDERID, P_NAME, TIN) SELECT tac.PROVIDERID, tac.P_NAME, tac.TIN, tac.CON_TO, COALESCE(ai.CON_SP, 0) AS CON_SP, COALESCE(ai.CON_OP, 0) AS CON_OP, COALESCE(ai.CON_FP, 0) AS CON_FP FROM TopAgencyCounts tac LEFT JOIN AgencyImpacts ai ON tac.PROVIDERID = ai.PROVIDERID AND tac.P_NAME = ai.P_NAME AND tac.TIN = ai.TIN ORDER BY tac.CON_TO DESC, tac.P_NAME';
    
    // New Chart Table Queries for Caregiver Dashboard
    public const QUERY_PAYER_CAREGIVER_COUNT = 'WITH TopCaregiverCounts AS (SELECT SSN, C_NAME, COUNT(DISTINCT VISIT_KEY) AS CON_TO FROM CONFLICTREPORT{DB_SUFFIX}.PUBLIC.PAYER_DASHBOARD_CAREGIVER_COUNT WHERE PAYERID = \'{PAYER_ID}\' AND VISITDATE BETWEEN \'{START_DATE}\' AND \'{END_DATE}\' GROUP BY SSN, C_NAME ORDER BY CON_TO DESC LIMIT 10), CaregiverImpacts AS (SELECT SSN, C_NAME, SUM(CON_SP) AS CON_SP, SUM(CON_OP) AS CON_OP, SUM(CON_FP) AS CON_FP FROM CONFLICTREPORT{DB_SUFFIX}.PUBLIC.PAYER_DASHBOARD_CAREGIVER_IMPACT WHERE PAYERID = \'{PAYER_ID}\' AND VISITDATE BETWEEN \'{START_DATE}\' AND \'{END_DATE}\' GROUP BY SSN, C_NAME) SELECT tcc.SSN, tcc.C_NAME, tcc.CON_TO, ci.CON_SP AS CON_SP, ci.CON_OP AS CON_OP, ci.CON_FP AS CON_FP FROM TopCaregiverCounts tcc LEFT JOIN CaregiverImpacts ci ON tcc.SSN = ci.SSN AND tcc.C_NAME = ci.C_NAME ORDER BY tcc.CON_TO DESC, tcc.C_NAME';
    
    // New Chart Table Queries for Payer Dashboard
    public const QUERY_PAYER_PAYER_COUNT = 'WITH TopPayerCounts AS (SELECT CONPAYERID, PNAME, COUNT(DISTINCT VISIT_KEY) AS CON_TO FROM CONFLICTREPORT{DB_SUFFIX}.PUBLIC.PAYER_DASHBOARD_PAYER_COUNT WHERE PAYERID = \'{PAYER_ID}\' AND CONPAYERID != \'{PAYER_ID}\' AND VISITDATE BETWEEN \'{START_DATE}\' AND \'{END_DATE}\' GROUP BY CONPAYERID, PNAME ORDER BY CON_TO DESC LIMIT 10), PayerImpacts AS (SELECT CONPAYERID, PNAME, SUM(CON_SP) AS CON_SP, SUM(CON_OP) AS CON_OP, SUM(CON_FP) AS CON_FP FROM CONFLICTREPORT{DB_SUFFIX}.PUBLIC.PAYER_DASHBOARD_PAYER_IMPACT WHERE PAYERID = \'{PAYER_ID}\' AND CONPAYERID != \'{PAYER_ID}\' AND VISITDATE BETWEEN \'{START_DATE}\' AND \'{END_DATE}\' GROUP BY CONPAYERID, PNAME) SELECT tpc.CONPAYERID, tpc.PNAME, tpc.CON_TO, COALESCE(pi.CON_SP, 0) AS CON_SP, COALESCE(pi.CON_OP, 0) AS CON_OP, COALESCE(pi.CON_FP, 0) AS CON_FP FROM TopPayerCounts tpc LEFT JOIN PayerImpacts pi ON tpc.CONPAYERID = pi.CONPAYERID AND tpc.PNAME = pi.PNAME ORDER BY tpc.CON_TO DESC, tpc.PNAME';
    
    // New Chart Table Queries for Patient Dashboard
    public const QUERY_PAYER_PATIENT_COUNT = 'WITH TopPatientCounts AS (SELECT PATIENTID, PFNAME, PLNAME, PNAME, ADMISSIONID, COUNT(DISTINCT VISIT_KEY) AS CON_TO FROM CONFLICTREPORT{DB_SUFFIX}.PUBLIC.PAYER_DASHBOARD_PATIENT_COUNT WHERE PAYERID = \'{PAYER_ID}\' AND VISITDATE BETWEEN \'{START_DATE}\' AND \'{END_DATE}\' GROUP BY PATIENTID, PFNAME, PLNAME, PNAME, ADMISSIONID ORDER BY CON_TO DESC LIMIT 10), PatientImpacts AS (SELECT PATIENTID, PFNAME, PLNAME, PNAME, ADMISSIONID, SUM(CON_SP) AS CON_SP, SUM(CON_OP) AS CON_OP, SUM(CON_FP) AS CON_FP FROM CONFLICTREPORT{DB_SUFFIX}.PUBLIC.PAYER_DASHBOARD_PATIENT_IMPACT WHERE PAYERID = \'{PAYER_ID}\' AND VISITDATE BETWEEN \'{START_DATE}\' AND \'{END_DATE}\' GROUP BY PATIENTID, PFNAME, PLNAME, PNAME, ADMISSIONID) SELECT tpc.PATIENTID, tpc.PFNAME, tpc.PLNAME, tpc.PNAME, tpc.ADMISSIONID, tpc.CON_TO, pi.CON_SP AS CON_SP, pi.CON_OP AS CON_OP, pi.CON_FP AS CON_FP FROM TopPatientCounts tpc LEFT JOIN PatientImpacts pi ON tpc.PATIENTID = pi.PATIENTID AND tpc.PFNAME = pi.PFNAME AND tpc.PLNAME = pi.PLNAME AND tpc.PNAME = pi.PNAME AND tpc.ADMISSIONID = pi.ADMISSIONID ORDER BY tpc.CON_TO DESC, tpc.PNAME';
}