<?php

namespace App\Constants;

class StateDashboardQueriesConstants
{
    // KPI Queries
    public const QUERY_KPI_COUNT = 'SELECT COUNT(DISTINCT VISIT_KEY) as TOTAL_CONFLICTS FROM CONFLICTREPORT{DB_SUFFIX}.PUBLIC.STATE_DASHBOARD_CON_TYPE_COUNT WHERE {WHERE_CONDITION}';
    
    public const QUERY_KPI_IMPACT = 'SELECT SUM(CON_SP) as FULL_SHIFT_IMPACT, SUM(CON_OP) as OVERLAP_IMPACT, SUM(CON_FP) as FINAL_IMPACT FROM CONFLICTREPORT{DB_SUFFIX}.PUBLIC.STATE_DASHBOARD_CON_TYPE_IMPACT WHERE {WHERE_CONDITION}';
    
    // Conflict Type Widget Queries
    public const QUERY_CONFLICT_TYPE_COUNT = 'SELECT CONTYPE, CONTYPEDESC, COUNT(DISTINCT VISIT_KEY) AS VALUE FROM CONFLICTREPORT{DB_SUFFIX}.PUBLIC.STATE_DASHBOARD_CON_TYPE_COUNT WHERE {WHERE_CONDITION} GROUP BY CONTYPE, CONTYPEDESC ORDER BY VALUE DESC';
    
    public const QUERY_CONFLICT_TYPE_IMPACT = 'SELECT CONTYPE, CONTYPEDESC, SUM(CON_{METRIC_SUFFIX}) AS VALUE FROM CONFLICTREPORT{DB_SUFFIX}.PUBLIC.STATE_DASHBOARD_CON_TYPE_IMPACT WHERE {WHERE_CONDITION} GROUP BY CONTYPE, CONTYPEDESC ORDER BY VALUE DESC';
    
    // Conflict Type Export Query - Combined (Count + Impact)
    public const QUERY_EXPORT_CONFLICT_TYPE = 'WITH counts_cte AS (SELECT CONTYPE, CONTYPEDESC, COUNT(DISTINCT VISIT_KEY) AS CON_TO FROM CONFLICTREPORT{DB_SUFFIX}.PUBLIC.STATE_DASHBOARD_CON_TYPE_COUNT WHERE {WHERE_CONDITION} GROUP BY CONTYPE, CONTYPEDESC), impacts_cte AS (SELECT CONTYPE, CONTYPEDESC, SUM(CON_SP) AS CON_SP, SUM(CON_OP) AS CON_OP, SUM(CON_FP) AS CON_FP FROM CONFLICTREPORT{DB_SUFFIX}.PUBLIC.STATE_DASHBOARD_CON_TYPE_IMPACT WHERE {WHERE_CONDITION} GROUP BY CONTYPE, CONTYPEDESC) SELECT c.CONTYPE, c.CONTYPEDESC, c.CON_TO, COALESCE(i.CON_SP, 0) AS CON_SP, COALESCE(i.CON_OP, 0) AS CON_OP, COALESCE(i.CON_FP, 0) AS CON_FP FROM counts_cte AS c LEFT JOIN impacts_cte AS i ON c.CONTYPE = i.CONTYPE AND c.CONTYPEDESC = i.CONTYPEDESC ORDER BY {ORDER_BY_FIELD} DESC';
    
    // Top Agencies Widget Queries
    public const QUERY_TOP_AGENCIES_COUNT = 'SELECT P_NAME, COUNT(DISTINCT VISIT_KEY) AS VALUE FROM CONFLICTREPORT{DB_SUFFIX}.PUBLIC.STATE_DASHBOARD_AGENCY_COUNT WHERE {WHERE_CONDITION} GROUP BY PROVIDERID, P_NAME ORDER BY VALUE DESC, P_NAME LIMIT 10';
    
    public const QUERY_TOP_AGENCIES_IMPACT = 'SELECT P_NAME, {SUM_FIELD} FROM CONFLICTREPORT{DB_SUFFIX}.PUBLIC.STATE_DASHBOARD_AGENCY_IMPACT WHERE {WHERE_CONDITION} GROUP BY PROVIDERID, P_NAME ORDER BY VALUE DESC, P_NAME LIMIT 10';
    
    // Top Agencies Export Query - Combined (Count + Impact)
    public const QUERY_EXPORT_TOP_AGENCIES = 'WITH TopAgencyCounts AS (SELECT PROVIDERID, P_NAME, COUNT(DISTINCT VISIT_KEY) AS CON_TO FROM CONFLICTREPORT{DB_SUFFIX}.PUBLIC.STATE_DASHBOARD_AGENCY_COUNT WHERE {WHERE_CONDITION} GROUP BY PROVIDERID, P_NAME), AgencyImpacts AS (SELECT PROVIDERID, P_NAME, SUM(CON_SP) AS CON_SP, SUM(CON_OP) AS CON_OP, SUM(CON_FP) AS CON_FP FROM CONFLICTREPORT{DB_SUFFIX}.PUBLIC.STATE_DASHBOARD_AGENCY_IMPACT WHERE {WHERE_CONDITION} GROUP BY PROVIDERID, P_NAME) SELECT tac.PROVIDERID, tac.P_NAME, tac.CON_TO, COALESCE(ai.CON_SP, 0) AS CON_SP, COALESCE(ai.CON_OP, 0) AS CON_OP, COALESCE(ai.CON_FP, 0) AS CON_FP FROM TopAgencyCounts tac LEFT JOIN AgencyImpacts ai ON tac.PROVIDERID = ai.PROVIDERID AND tac.P_NAME = ai.P_NAME ORDER BY {ORDER_BY_FIELD} DESC, tac.P_NAME LIMIT 10';
    
    // Top Members Widget Queries
    public const QUERY_TOP_MEMBERS_COUNT = 'SELECT PNAME AS MEMBER_NAME, COUNT(DISTINCT VISIT_KEY) AS VALUE FROM CONFLICTREPORT{DB_SUFFIX}.PUBLIC.STATE_DASHBOARD_PATIENT_COUNT WHERE {WHERE_CONDITION} GROUP BY PATIENTID, PNAME ORDER BY VALUE DESC, PNAME LIMIT 10';
    
    public const QUERY_TOP_MEMBERS_IMPACT = 'SELECT PNAME AS MEMBER_NAME, {SUM_FIELD} FROM CONFLICTREPORT{DB_SUFFIX}.PUBLIC.STATE_DASHBOARD_PATIENT_IMPACT WHERE {WHERE_CONDITION} GROUP BY PATIENTID, PNAME ORDER BY VALUE DESC, PNAME LIMIT 10';
    
    // Top Members Export Query - Combined (Count + Impact)
    public const QUERY_EXPORT_TOP_MEMBERS = 'WITH TopMemberCounts AS (SELECT PATIENTID, PNAME, COUNT(DISTINCT VISIT_KEY) AS CON_TO FROM CONFLICTREPORT{DB_SUFFIX}.PUBLIC.STATE_DASHBOARD_PATIENT_COUNT WHERE {WHERE_CONDITION} AND PNAME IS NOT NULL AND TRIM(PNAME) != \'\' GROUP BY PATIENTID, PNAME), MemberImpacts AS (SELECT PATIENTID, PNAME, SUM(CON_SP) AS CON_SP, SUM(CON_OP) AS CON_OP, SUM(CON_FP) AS CON_FP FROM CONFLICTREPORT{DB_SUFFIX}.PUBLIC.STATE_DASHBOARD_PATIENT_IMPACT WHERE {WHERE_CONDITION} AND PNAME IS NOT NULL AND TRIM(PNAME) != \'\' GROUP BY PATIENTID, PNAME) SELECT tmc.PATIENTID, tmc.PNAME, tmc.CON_TO, COALESCE(mi.CON_SP, 0) AS CON_SP, COALESCE(mi.CON_OP, 0) AS CON_OP, COALESCE(mi.CON_FP, 0) AS CON_FP FROM TopMemberCounts tmc LEFT JOIN MemberImpacts mi ON tmc.PATIENTID = mi.PATIENTID AND tmc.PNAME = mi.PNAME ORDER BY {ORDER_BY_FIELD} DESC, tmc.PNAME LIMIT 10';
    
    // Top Payers Widget Queries
    public const QUERY_TOP_PAYERS_COUNT = 'SELECT d."Payer Name" AS PNAME, COUNT(DISTINCT VISIT_KEY) AS VALUE FROM CONFLICTREPORT{DB_SUFFIX}.PUBLIC.STATE_DASHBOARD_PAYER_COUNT t JOIN ANALYTICS{DB_SUFFIX}.BI.DIMPAYER d ON t.PAYERID = d."Payer Id" WHERE {WHERE_CONDITION} GROUP BY d."Payer Id", d."Payer Name" ORDER BY VALUE DESC, PNAME LIMIT 10';
    
    public const QUERY_TOP_PAYERS_IMPACT = 'SELECT d."Payer Name" AS PNAME, {SUM_FIELD} FROM CONFLICTREPORT{DB_SUFFIX}.PUBLIC.STATE_DASHBOARD_PAYER_IMPACT t JOIN ANALYTICS{DB_SUFFIX}.BI.DIMPAYER d ON t.PAYERID = d."Payer Id" WHERE {WHERE_CONDITION} GROUP BY d."Payer Id", d."Payer Name" ORDER BY VALUE DESC, PNAME LIMIT 10';
    
    // Top Payers Export Query - Combined (Count + Impact) - Uses STATE_DASHBOARD_PAYER tables with JOIN to DIMPAYER
    public const QUERY_EXPORT_TOP_PAYERS = 'WITH TopPayerCounts AS (SELECT t.PAYERID, d."Payer Name" AS PNAME, COUNT(DISTINCT VISIT_KEY) AS CON_TO FROM CONFLICTREPORT{DB_SUFFIX}.PUBLIC.STATE_DASHBOARD_PAYER_COUNT t JOIN ANALYTICS{DB_SUFFIX}.BI.DIMPAYER d ON t.PAYERID = d."Payer Id" WHERE {WHERE_CONDITION} GROUP BY t.PAYERID, d."Payer Name"), PayerImpacts AS (SELECT t.PAYERID, d."Payer Name" AS PNAME, SUM(CON_SP) AS CON_SP, SUM(CON_OP) AS CON_OP, SUM(CON_FP) AS CON_FP FROM CONFLICTREPORT{DB_SUFFIX}.PUBLIC.STATE_DASHBOARD_PAYER_IMPACT t JOIN ANALYTICS{DB_SUFFIX}.BI.DIMPAYER d ON t.PAYERID = d."Payer Id" WHERE {WHERE_CONDITION} GROUP BY t.PAYERID, d."Payer Name") SELECT tpc.PAYERID, tpc.PNAME, tpc.CON_TO, COALESCE(pi.CON_SP, 0) AS CON_SP, COALESCE(pi.CON_OP, 0) AS CON_OP, COALESCE(pi.CON_FP, 0) AS CON_FP FROM TopPayerCounts tpc LEFT JOIN PayerImpacts pi ON tpc.PAYERID = pi.PAYERID AND tpc.PNAME = pi.PNAME ORDER BY {ORDER_BY_FIELD} DESC, tpc.PNAME LIMIT 10';
    
    // Top Caregivers Widget Queries
    public const QUERY_TOP_CAREGIVERS_COUNT = 'SELECT C_NAME, COUNT(DISTINCT VISIT_KEY) AS VALUE FROM CONFLICTREPORT{DB_SUFFIX}.PUBLIC.STATE_DASHBOARD_CAREGIVER_COUNT WHERE {WHERE_CONDITION} AND C_NAME IS NOT NULL AND TRIM(C_NAME) != \'\' GROUP BY SSN, C_NAME ORDER BY VALUE DESC, C_NAME LIMIT 10';
    
    public const QUERY_TOP_CAREGIVERS_IMPACT = 'SELECT C_NAME, {SUM_FIELD} FROM CONFLICTREPORT{DB_SUFFIX}.PUBLIC.STATE_DASHBOARD_CAREGIVER_IMPACT WHERE {WHERE_CONDITION} AND C_NAME IS NOT NULL AND TRIM(C_NAME) != \'\' GROUP BY SSN, C_NAME ORDER BY VALUE DESC, C_NAME LIMIT 10';
    
    // Top Caregivers Export Query - Combined (Count + Impact)
    public const QUERY_EXPORT_TOP_CAREGIVERS = 'WITH TopCaregiverCounts AS (SELECT SSN, C_NAME, COUNT(DISTINCT VISIT_KEY) AS CON_TO FROM CONFLICTREPORT{DB_SUFFIX}.PUBLIC.STATE_DASHBOARD_CAREGIVER_COUNT WHERE {WHERE_CONDITION} AND C_NAME IS NOT NULL AND TRIM(C_NAME) != \'\' GROUP BY SSN, C_NAME), CaregiverImpacts AS (SELECT SSN, C_NAME, SUM(CON_SP) AS CON_SP, SUM(CON_OP) AS CON_OP, SUM(CON_FP) AS CON_FP FROM CONFLICTREPORT{DB_SUFFIX}.PUBLIC.STATE_DASHBOARD_CAREGIVER_IMPACT WHERE {WHERE_CONDITION} AND C_NAME IS NOT NULL AND TRIM(C_NAME) != \'\' GROUP BY SSN, C_NAME) SELECT tcc.C_NAME, tcc.CON_TO, COALESCE(ci.CON_SP, 0) AS CON_SP, COALESCE(ci.CON_OP, 0) AS CON_OP, COALESCE(ci.CON_FP, 0) AS CON_FP FROM TopCaregiverCounts tcc INNER JOIN CaregiverImpacts ci ON tcc.SSN = ci.SSN AND tcc.C_NAME = ci.C_NAME ORDER BY {ORDER_BY_FIELD} DESC, tcc.C_NAME LIMIT 10';
    
    // Available Data Queries
    public const QUERY_AVAILABLE_PAYERS = 'SELECT "Payer Id", "Payer Name", "Application Payer Id" FROM ANALYTICS{DB_SUFFIX}.BI.DIMPAYER WHERE "Is Active" = TRUE AND "Is Demo" = FALSE AND "Payer Id" IN ({PAYER_IDS}) ORDER BY UPPER("Payer Name")';
    
    public const QUERY_AVAILABLE_PROVIDERS = 'SELECT DISTINCT PROVIDERID, P_NAME as "Provider Name" FROM CONFLICTREPORT{DB_SUFFIX}.PUBLIC.STATE_DASHBOARD_AGENCY_IMPACT WHERE PAYERID IN ({PAYER_IDS}) AND PROVIDERID IS NOT NULL AND TRIM(PROVIDERID) != \'\' AND P_NAME IS NOT NULL AND TRIM(P_NAME) != \'\' ORDER BY UPPER(P_NAME)';
    
    public const QUERY_AVAILABLE_COUNTIES = 'SELECT DISTINCT UPPER(COUNTY) as COUNTY FROM CONFLICTREPORT{DB_SUFFIX}.PUBLIC.STATE_DASHBOARD_AGENCY_IMPACT WHERE PAYERID IN ({PAYER_IDS}) AND COUNTY IS NOT NULL AND TRIM(COUNTY) != \'\' ORDER BY UPPER(COUNTY)';
    
    public const QUERY_NULL_COUNTY_COUNT = 'SELECT COUNT(*) as NULL_COUNT FROM CONFLICTREPORT{DB_SUFFIX}.PUBLIC.STATE_DASHBOARD_AGENCY_COUNT WHERE PAYERID IN ({PAYER_IDS}) AND (COUNTY IS NULL OR TRIM(COUNTY) = \'\')';
    
    public const QUERY_AVAILABLE_SERVICE_CODES = 'SELECT DISTINCT UPPER(SERVICECODE) as SERVICECODE FROM CONFLICTREPORT{DB_SUFFIX}.PUBLIC.STATE_DASHBOARD_AGENCY_IMPACT WHERE PAYERID IN ({PAYER_IDS}) AND SERVICECODE IS NOT NULL AND TRIM(SERVICECODE) != \'\' ORDER BY UPPER(SERVICECODE)';
    
    public const QUERY_NULL_SERVICE_CODE_COUNT = 'SELECT COUNT(*) as NULL_COUNT FROM CONFLICTREPORT{DB_SUFFIX}.PUBLIC.STATE_DASHBOARD_AGENCY_COUNT WHERE PAYERID IN ({PAYER_IDS}) AND (SERVICECODE IS NULL OR TRIM(SERVICECODE) = \'\')';
    
    // Venn Diagram Record Count Query
    public const QUERY_VENN_RECORD_COUNT = 'SELECT COUNT(*) as RECORD_COUNT FROM CONFLICTREPORT{DB_SUFFIX}.PUBLIC.STATE_DASHBOARD_CON_TYPE WHERE {WHERE_CONDITION}';
}

