-- Schema-agnostic Postgres DDL translated from SF Conflict Tables.sql
-- Usage:
--   - Change the value of target_schema in the DO block below (default: conflict_dev)
--   - Run the script in psql/pgAdmin/DBeaver; it will create the schema if missing and set search_path
--   - All objects are created unqualified, honoring the configured search_path

DO $$
DECLARE
	target_schema text := 'conflict_dev'; -- change this to your desired schema name
BEGIN
	IF NOT EXISTS (
		SELECT 1 FROM pg_namespace WHERE nspname = target_schema
	) THEN
		EXECUTE format('CREATE SCHEMA %I', target_schema);
	END IF;
	-- Set search_path for this session to the target schema
	PERFORM set_config('search_path', quote_ident(target_schema), false);
END $$;

-- ==========================
-- Sequences for autoincrement columns
-- ==========================

-- ==========================
-- Tables
-- ==========================

-- CONFLICTS
CREATE TABLE IF NOT EXISTS conflicts (
	"CONFLICTID" int8 generated by default as identity NOT NULL,
	"RECORDEDDATETIME" timestamp DEFAULT CURRENT_TIMESTAMP,
	"StatusFlag" varchar(5) DEFAULT 'U'::character varying NULL,
	"NoResponseFlag" varchar(10) NULL,
	"NoResponseReasonID" int8 NULL,
	"NoResponseTitle" varchar(50) NULL,
	"NoResponseNotes" varchar(500) NULL,
	"ResolveDate" timestamp NULL,
	"CreatedDate" timestamp NULL,
	"ResolvedBy" varchar(200) NULL,
	"NoResponseDate" timestamp NULL,
	"FlagForReview" varchar(5) NULL,
	"FlagForReviewDate" timestamp NULL,
	"UpdatedRFlag" varchar(5) NULL,
	CONSTRAINT PRIMARY KEY ("CONFLICTID")
);

-- CONFLICTVISITMAPS
CREATE TABLE IF NOT EXISTS conflictvisitmaps (
	"ID" int8 generated by default as identity NOT NULL,
	"CONFLICTID" int8 NULL,
	"GroupID" int8 NULL,
	"SSN" varchar(20) NULL,
	"ProviderID" uuid NULL,
	"AppProviderID" int8 NULL,
	"ProviderName" varchar(100) NULL,
	"ConProviderID" uuid NULL,
	"ConAppProviderID" int8 NULL,
	"ConProviderName" varchar(100) NULL,
	"VisitID" uuid NULL,
	"AppVisitID" int8 NULL,
	"ConVisitID" uuid NULL,
	"ConAppVisitID" int8 NULL,
	"VisitDate" date NULL,
	"SchStartTime" timestamp NULL,
	"SchEndTime" timestamp NULL,
	"ConSchStartTime" timestamp NULL,
	"ConSchEndTime" timestamp NULL,
	"VisitStartTime" timestamp NULL,
	"VisitEndTime" timestamp NULL,
	"ConVisitStartTime" timestamp NULL,
	"ConVisitEndTime" timestamp NULL,
	"EVVStartTime" timestamp NULL,
	"EVVEndTime" timestamp NULL,
	"ConEVVStartTime" timestamp NULL,
	"ConEVVEndTime" timestamp NULL,
	"ShVTSTTime" timestamp NULL,
	"ShVTENTime" timestamp NULL,
	"CShVTSTTime" timestamp NULL,
	"CShVTENTime" timestamp NULL,
	"CaregiverID" uuid NULL,
	"AppCaregiverID" int8 NULL,
	"AideCode" varchar(50) NULL,
	"AideName" varchar(101) NULL,
	"AideFName" varchar(50) NULL,
	"AideLName" varchar(50) NULL,
	"AideSSN" varchar(50) NULL,
	"AideStatus" varchar(20) NULL,
	"ConCaregiverID" uuid NULL,
	"ConAppCaregiverID" int8 NULL,
	"ConAideCode" varchar(50) NULL,
	"ConAideName" varchar(101) NULL,
	"ConAideFName" varchar(50) NULL,
	"ConAideLName" varchar(50) NULL,
	"ConAideSSN" varchar(50) NULL,
	"ConAideStatus" varchar(20) NULL,
	"OfficeID" uuid NULL,
	"AppOfficeID" int8 NULL,
	"Office" varchar(100) NULL,
	"ConOfficeID" uuid NULL,
	"ConAppOfficeID" int8 NULL,
	"ConOffice" varchar(100) NULL,
	"PatientID" uuid NULL,
	"AppPatientID" int8 NULL,
	"PAdmissionID" varchar(100) NULL,
	"PName" varchar(201) NULL,
	"PFName" varchar(100) NULL,
	"PLName" varchar(100) NULL,
	"PMedicaidNumber" varchar(100) NULL,
	"PStatus" varchar(20) NULL,
	"PAddressID" uuid NULL,
	"PAppAddressID" int8 NULL,
	"PAddressL1" varchar(500) NULL,
	"PAddressL2" varchar(100) NULL,
	"PCity" varchar(255) NULL,
	"PAddressState" varchar(100) NULL,
	"PZipCode" varchar(100) NULL,
	"PCounty" varchar(100) NULL,
	"PLongitude" real NULL,
	"PLatitude" real NULL,
	"ConPatientID" uuid NULL,
	"ConAppPatientID" int8 NULL,
	"ConPAdmissionID" varchar(100) NULL,
	"ConPName" varchar(201) NULL,
	"ConPFName" varchar(100) NULL,
	"ConPLName" varchar(100) NULL,
	"ConPMedicaidNumber" varchar(100) NULL,
	"ConPStatus" varchar(20) NULL,
	"ConPAddressID" uuid NULL,
	"ConPAppAddressID" int8 NULL,
	"ConPAddressL1" varchar(500) NULL,
	"ConPAddressL2" varchar(100) NULL,
	"ConPCity" varchar(255) NULL,
	"ConPAddressState" varchar(100) NULL,
	"ConPZipCode" varchar(100) NULL,
	"ConPCounty" varchar(100) NULL,
	"ConPLongitude" real NULL,
	"ConPLatitude" real NULL,
	"PayerID" uuid NULL,
	"AppPayerID" int8 NULL,
	"Contract" varchar(50) NULL,
	"PayerState" varchar(10) NULL,
	"ConPayerID" uuid NULL,
	"ConAppPayerID" int8 NULL,
	"ConContract" varchar(50) NULL,
	"ConPayerState" varchar(100) NULL,
	"Billed" varchar(3) NULL,
	"BilledDate" timestamp NULL,
	"BilledHours" real NULL,
	"BilledRate" real NULL,
	"TotalBilledAmount" real NULL,
	"BillRateNonBilled" real NULL,
	"BillRateBoth" real NULL,
	"BilledRateMinute" real NULL,
	"RateType" varchar(10) NULL,
	"ConBilled" varchar(3) NULL,
	"ConBilledDate" timestamp NULL,
	"ConBilledHours" real NULL,
	"ConBilledRate" real NULL,
	"ConTotalBilledAmount" real NULL,
	"ConBillRateNonBilled" real NULL,
	"ConBillRateBoth" real NULL,
	"ConBilledRateMinute" real NULL,
	"ConRateType" varchar(10) NULL,
	"MinuteDiffBetweenSch" int4 NULL,
	"DistanceMilesFromLatLng" real NULL,
	"AverageMilesPerHour" real NULL,
	"ETATravelMinutes" int4 NULL,
	"InserviceStartDate" timestamp NULL,
	"InserviceEndDate" timestamp NULL,
	"PTOStartDate" timestamp NULL,
	"PTOEndDate" timestamp NULL,
	"ServiceCodeID" uuid NULL,
	"AppServiceCodeID" int8 NULL,
	"ServiceCode" varchar(50) NULL,
	"ConServiceCodeID" uuid NULL,
	"ConAppServiceCodeID" int8 NULL,
	"ConServiceCode" varchar(50) NULL,
	"SameSchTimeFlag" varchar(1) NULL,
	"SameVisitTimeFlag" varchar(1) NULL,
	"SchAndVisitTimeSameFlag" varchar(1) NULL,
	"SchOverAnotherSchTimeFlag" varchar(1) NULL,
	"VisitTimeOverAnotherVisitTimeFlag" varchar(1) NULL,
	"SchTimeOverVisitTimeFlag" varchar(1) NULL,
	"DistanceFlag" varchar(1) NULL,
	"InServiceFlag" varchar(1) NULL,
	"PTOFlag" varchar(1) NULL,
	"AgencyContact" varchar(100) NULL,
	"AgencyPhone" varchar(30) NULL,
	"ConAgencyContact" varchar(100) NULL,
	"ConAgencyPhone" varchar(30) NULL,
	"IsMissed" bool NULL,
	"MissedVisitReason" varchar(500) NULL,
	"EVVType" varchar(20) NULL,
	"ConIsMissed" bool NULL,
	"ConMissedVisitReason" varchar(500) NULL,
	"ConEVVType" varchar(20) NULL,
	"ConNoResponseFlag" varchar(5) NULL,
	"ConNoResponseReasonID" int8 NULL,
	"ConNoResponseTitle" varchar(50) NULL,
	"ConNoResponseNotes" varchar(500) NULL,
	"P_PatientID" uuid NULL,
	"P_AppPatientID" int8 NULL,
	"P_PAdmissionID" varchar(100) NULL,
	"P_PName" varchar(201) NULL,
	"P_PAddressID" uuid NULL,
	"P_PAppAddressID" int8 NULL,
	"P_PAddressL1" varchar(500) NULL,
	"P_PAddressL2" varchar(100) NULL,
	"P_PCity" varchar(255) NULL,
	"P_PAddressState" varchar(100) NULL,
	"P_PZipCode" varchar(100) NULL,
	"P_PCounty" varchar(100) NULL,
	"P_PFName" varchar(100) NULL,
	"P_PLName" varchar(100) NULL,
	"P_PMedicaidNumber" varchar(100) NULL,
	"P_PStatus" varchar(50) NULL,
	"ConP_PatientID" uuid NULL,
	"ConP_AppPatientID" int8 NULL,
	"ConP_PAdmissionID" varchar(100) NULL,
	"ConP_PName" varchar(201) NULL,
	"ConP_PAddressID" uuid NULL,
	"ConP_PAppAddressID" int8 NULL,
	"ConP_PAddressL1" varchar(500) NULL,
	"ConP_PAddressL2" varchar(100) NULL,
	"ConP_PCity" varchar(255) NULL,
	"ConP_PAddressState" varchar(100) NULL,
	"ConP_PZipCode" varchar(100) NULL,
	"ConP_PCounty" varchar(100) NULL,
	"ConP_PFName" varchar(100) NULL,
	"ConP_PLName" varchar(100) NULL,
	"ConP_PMedicaidNumber" varchar(100) NULL,
	"ConP_PStatus" varchar(20) NULL,
	"PA_PatientID" uuid NULL,
	"PA_AppPatientID" int8 NULL,
	"PA_PAdmissionID" varchar(100) NULL,
	"PA_PName" varchar(201) NULL,
	"PA_PAddressID" uuid NULL,
	"PA_PAppAddressID" int8 NULL,
	"PA_PAddressL1" varchar(500) NULL,
	"PA_PAddressL2" varchar(100) NULL,
	"PA_PCity" varchar(255) NULL,
	"PA_PAddressState" varchar(100) NULL,
	"PA_PZipCode" varchar(100) NULL,
	"PA_PCounty" varchar(100) NULL,
	"PA_PFName" varchar(100) NULL,
	"PA_PLName" varchar(100) NULL,
	"PA_PMedicaidNumber" varchar(100) NULL,
	"PA_PStatus" varchar(20) NULL,
	"ConPA_PatientID" uuid NULL,
	"ConPA_AppPatientID" int8 NULL,
	"ConPA_PAdmissionID" varchar(100) NULL,
	"ConPA_PName" varchar(201) NULL,
	"ConPA_PAddressID" uuid NULL,
	"ConPA_PAppAddressID" int8 NULL,
	"ConPA_PAddressL1" varchar(500) NULL,
	"ConPA_PAddressL2" varchar(100) NULL,
	"ConPA_PCity" varchar(255) NULL,
	"ConPA_PAddressState" varchar(100) NULL,
	"ConPA_PZipCode" varchar(100) NULL,
	"ConPA_PCounty" varchar(100) NULL,
	"ConPA_PFName" varchar(100) NULL,
	"ConPA_PLName" varchar(100) NULL,
	"ConPA_PMedicaidNumber" varchar(100) NULL,
	"ConPA_PStatus" varchar(20) NULL,
	"ContractType" varchar(30) NULL,
	"ConContractType" varchar(30) NULL,
	"LastUpdatedBy" varchar(100) NULL,
	"LastUpdatedDate" timestamp NULL,
	"ConLastUpdatedBy" varchar(100) NULL,
	"ConLastUpdatedDate" timestamp NULL,
	"CreatedDate" timestamp DEFAULT CURRENT_TIMESTAMP NULL,
	"ResolveDate" timestamp NULL,
	"CRDATEUNIQUE" timestamp NULL,
	"G_CRDATEUNIQUE" timestamp NULL,
	"UpdateFlag" int2 NULL,
	"UpdatedDate" timestamp NULL,
	"StatusFlag" varchar(5) DEFAULT 'U'::character varying NULL,
	"ResolvedBy" varchar(200) NULL,
	"TempGroupID" int8 NULL,
	"ReverseUUID" varchar(100) NULL,
	"ConNoResponseDate" timestamp NULL,
	"FederalTaxNumber" varchar(100) NULL,
	"ConFederalTaxNumber" varchar(100) NULL,
	"ConInserviceStartDate" timestamp NULL,
	"ConInserviceEndDate" timestamp NULL,
	"ConPTOStartDate" timestamp NULL,
	"ConPTOEndDate" timestamp NULL,
	"FlagForReview" varchar(5) NULL,
	"FlagForReviewDate" timestamp NULL,
	"BILLABLEMINUTESFULLSHIFT" real NULL,
	"BILLABLEUNITSFULLSHIFT" real NULL,
	"BILLABLEMINUTESOVERLAP" real NULL,
	"BILLABLEUNITSOVERLAP" real NULL,
	"FAILEDON" timestamp NULL,
	"AggFlagForReview" varchar(5) NULL,
	"AggFlagForReviewDate" timestamp NULL,
	CONSTRAINT PRIMARY KEY ("ID")
);


-- CONFLICTVISITMAPS_TEMP
CREATE TABLE IF NOT EXISTS conflictvisitmaps_temp (
	"ID" int8 NULL,
	"CONFLICTID" int8 NULL,
	"SSN" varchar(20) NULL,
	"ProviderID" uuid NULL,
	"AppProviderID" int8 NULL,
	"ProviderName" varchar(100) NULL,
	"FederalTaxNumber" varchar(100) NULL,
	"VisitID" uuid NULL,
	"AppVisitID" int8 NULL,
	"ConProviderID" uuid NULL,
	"ConAppProviderID" int8 NULL,
	"ConProviderName" varchar(100) NULL,
	"ConFederalTaxNumber" varchar(100) NULL,
	"ConVisitID" uuid NULL,
	"ConAppVisitID" int8 NULL,
	"VisitDate" date NULL,
	"SchStartTime" timestamp NULL,
	"SchEndTime" timestamp NULL,
	"ConSchStartTime" timestamp NULL,
	"ConSchEndTime" timestamp NULL,
	"VisitStartTime" timestamp NULL,
	"VisitEndTime" timestamp NULL,
	"ConVisitStartTime" timestamp NULL,
	"ConVisitEndTime" timestamp NULL,
	"EVVStartTime" timestamp NULL,
	"EVVEndTime" timestamp NULL,
	"ConEVVStartTime" timestamp NULL,
	"ConEVVEndTime" timestamp NULL,
	"CaregiverID" uuid NULL,
	"AppCaregiverID" int8 NULL,
	"AideCode" varchar(50) NULL,
	"AideName" varchar(101) NULL,
	"AideSSN" varchar(50) NULL,
	"ConCaregiverID" uuid NULL,
	"ConAppCaregiverID" int8 NULL,
	"ConAideCode" varchar(50) NULL,
	"ConAideName" varchar(101) NULL,
	"ConAideSSN" varchar(50) NULL,
	"OfficeID" uuid NULL,
	"AppOfficeID" int8 NULL,
	"Office" varchar(100) NULL,
	"ConOfficeID" uuid NULL,
	"ConAppOfficeID" int8 NULL,
	"ConOffice" varchar(100) NULL,
	"PatientID" uuid NULL,
	"AppPatientID" int8 NULL,
	"PAdmissionID" varchar(100) NULL,
	"PName" varchar(201) NULL,
	"PAddressID" uuid NULL,
	"PAppAddressID" int8 NULL,
	"PAddressL1" varchar(500) NULL,
	"PAddressL2" varchar(100) NULL,
	"PCity" varchar(255) NULL,
	"PAddressState" varchar(100) NULL,
	"PZipCode" varchar(100) NULL,
	"PCounty" varchar(100) NULL,
	"PLongitude" real NULL,
	"PLatitude" real NULL,
	"ConPatientID" uuid NULL,
	"ConAppPatientID" int8 NULL,
	"ConPAdmissionID" varchar(100) NULL,
	"ConPName" varchar(201) NULL,
	"ConPAddressID" uuid NULL,
	"ConPAppAddressID" int8 NULL,
	"ConPAddressL1" varchar(500) NULL,
	"ConPAddressL2" varchar(100) NULL,
	"ConPCity" varchar(255) NULL,
	"ConPAddressState" varchar(100) NULL,
	"ConPZipCode" varchar(100) NULL,
	"ConPCounty" varchar(100) NULL,
	"ConPLongitude" real NULL,
	"ConPLatitude" real NULL,
	"PayerID" uuid NULL,
	"AppPayerID" int8 NULL,
	"Contract" varchar(50) NULL,
	"ConPayerID" uuid NULL,
	"ConAppPayerID" int8 NULL,
	"ConContract" varchar(50) NULL,
	"BilledDate" timestamp NULL,
	"ConBilledDate" timestamp NULL,
	"BilledHours" real NULL,
	"ConBilledHours" real NULL,
	"Billed" varchar(3) NULL,
	"ConBilled" varchar(3) NULL,
	"MinuteDiffBetweenSch" int8 NULL,
	"DistanceMilesFromLatLng" real NULL,
	"AverageMilesPerHour" real NULL,
	"ETATravelMinutes" int4 NULL,
	"InserviceStartDate" timestamp NULL,
	"InserviceEndDate" timestamp NULL,
	"PTOStartDate" timestamp NULL,
	"PTOEndDate" timestamp NULL,
	"ConInserviceStartDate" timestamp NULL,
	"ConInserviceEndDate" timestamp NULL,
	"ConPTOStartDate" timestamp NULL,
	"ConPTOEndDate" timestamp NULL,
	"ServiceCodeID" uuid NULL,
	"AppServiceCodeID" int8 NULL,
	"RateType" varchar(50) NULL,
	"ServiceCode" varchar(50) NULL,
	"ConServiceCodeID" uuid NULL,
	"ConAppServiceCodeID" int8 NULL,
	"ConRateType" varchar(50) NULL,
	"ConServiceCode" varchar(50) NULL,
	"SameSchTimeFlag" varchar(1) NULL,
	"SameVisitTimeFlag" varchar(1) NULL,
	"SchAndVisitTimeSameFlag" varchar(1) NULL,
	"SchOverAnotherSchTimeFlag" varchar(1) NULL,
	"VisitTimeOverAnotherVisitTimeFlag" varchar(1) NULL,
	"SchTimeOverVisitTimeFlag" varchar(1) NULL,
	"DistanceFlag" varchar(1) NULL,
	"InServiceFlag" varchar(1) NULL,
	"PTOFlag" varchar(1) NULL,
	"StatusFlag" varchar(5) DEFAULT 'U'::character varying NULL,
	"ConStatusFlag" varchar(5) DEFAULT 'U'::character varying NULL,
	"AideFName" varchar(50) NULL,
	"AideLName" varchar(50) NULL,
	"ConAideFName" varchar(50) NULL,
	"ConAideLName" varchar(50) NULL,
	"PFName" varchar(100) NULL,
	"PLName" varchar(100) NULL,
	"ConPFName" varchar(100) NULL,
	"ConPLName" varchar(100) NULL,
	"PMedicaidNumber" varchar(100) NULL,
	"ConPMedicaidNumber" varchar(100) NULL
);

-- CONFLICT_COMMU_INTERS
CREATE TABLE IF NOT EXISTS conflict_commu_inters (
	"id" int8 generated by default as identity NOT NULL,
	"CONFLICTID" int8 NULL,
	"GroupID" int8 NULL,
	"ReverseUUID" varchar(100) NULL,
	"Description" varchar(1000) NULL,
	"CommentType" int2 NULL,
	"Attachmenturl" varchar(500) NULL,
	communications_type int2 NULL,
	created_at timestamp NULL,
	updated_at timestamp NULL,
	created_by int8 NULL,
	updated_by int8 NULL,
	created_by_name varchar(200) NULL,
	updated_by_name varchar(200) NULL,
	"OriginalFileName" varchar(200) NULL,
	"FileSize" int4 NULL,
	CONSTRAINT PRIMARY KEY (id)
);

-- CONTACT_MAINTENANCE
CREATE TABLE IF NOT EXISTS contact_maintenance (
	"ID" int8 generated by default as identity NOT NULL,
	"RECORDEDDATETIME" timestamp DEFAULT CURRENT_TIMESTAMP,
	"CONTACT_NAME" varchar(255) DEFAULT 'U',
	"PHONE" varchar(20) NULL,
	"ProviderID" uuid NULL,
	"AppProviderID" int8 NULL,
	"UPDATED_BY" int8 NULL,
	"UPDATED_AT" timestamp DEFAULT CURRENT_TIMESTAMP NULL,
	"PID" varchar(50) NULL,
	"APPLICATIONPID" int8 NULL,
	CONSTRAINT PRIMARY KEY ("ID")
);

-- EXCLUDED_AGENCY
CREATE TABLE IF NOT EXISTS excluded_agency (
	"ID" int8 generated by default as identity NOT NULL,
	"AgencyName" varchar(100) NULL,
	"ProviderID" uuid NULL,
	"AppProviderID" int8 NULL,
	CONSTRAINT PRIMARY KEY ("ID")
);

-- EXCLUDED_SSN
CREATE TABLE IF NOT EXISTS excluded_ssn (
	"ID" int8 generated by default as identity NOT NULL,
	"SSN" varchar(20) NULL,
	CONSTRAINT PRIMARY KEY ("ID")
);

-- FAILED_API_LOGS
CREATE TABLE IF NOT EXISTS failed_api_logs (
	"APPVISITID" int8 NULL,
	"APPPAYERID" int8 NULL,
	"CONTRACT_ID_INTERNAL" int8 NULL,
	"PAYLOAD" text NULL,
	"RESPONSE" text NULL,
	"FAILURE_TYPE" text NULL,
	"ERROR_MESSAGE" text NULL,
	"CONFLICTID" int8 NOT NULL,
	CONSTRAINT PRIMARY KEY ("CONFLICTID")
);

-- GOVBODIESPAYERS
CREATE TABLE IF NOT EXISTS govbodiespayers (
	"ID" int8 generated by default as identity NOT NULL,
	"PayerID" uuid NULL,
	"AppPayerID" int8 NULL,
	"UserID" int8 NULL,
	"PAYER_NAME" varchar(100) NULL,
	"STATUS_NAME" varchar(50) NULL,
	"CREATED_AT" timestamp DEFAULT CURRENT_TIMESTAMP NULL,
	"UPDATED_AT" timestamp DEFAULT CURRENT_TIMESTAMP NULL,
	CONSTRAINT PRIMARY KEY ("ID")
);

-- LOG_FIELDS
CREATE TABLE IF NOT EXISTS log_fields (
	"ID" int8 generated by default as identity NOT NULL,
	"FieldName" varchar(50) NULL,
	"FieldDisplayValue" varchar(50) NULL,
	"FieldFor" varchar(10) NULL,
	"FieldType" varchar(10) NULL,
	"RestrictedFlag" int2 NULL,
	"NotShowInDropDown" int2 NULL,
	"HideColumnFlag" int2 NULL,
	"HideHidePayerFlag" int2 NULL,
	"HideForProviderFlag" int2 NULL,
	CONSTRAINT PRIMARY KEY ("ID")
);

-- LOG_HISTORY
CREATE TABLE IF NOT EXISTS log_history (
	"ID" int8 generated by default as identity NOT NULL,
	"CONID" int8 NULL,
	"CreatedDateTime" timestamp DEFAULT CURRENT_TIMESTAMP NULL,
	"LogTypeFlag" varchar(10) NULL,
	CONSTRAINT PRIMARY KEY ("ID")
);

-- LOG_HISTORY_VALUES
CREATE TABLE IF NOT EXISTS log_history_values (
	"ID" int8 generated by default as identity NOT NULL,
	"LHID" int8 NULL,
	"LogID" int8 NULL,
	"OldValue" text NULL,
	"NewValue" text NULL,
	"VisitID" uuid NULL,
	"AppVisitID" int8 NULL,
	CONSTRAINT PRIMARY KEY ("ID")
);

-- LOG_HISTORY_VALUES_TEMP
CREATE TABLE IF NOT EXISTS log_history_values_temp (
	"CONID" int8 NOT NULL,
	"LogID" int8 NULL,
	"OldValue" text NULL,
	"NewValue" text NULL,
	"VisitID" uuid NULL,
	"AppVisitID" int8 NULL
);

-- MPH
CREATE TABLE IF NOT EXISTS mph (
	"ID" int8 generated by default as identity NOT NULL,
	"RECORDEDDATETIME" timestamp DEFAULT CURRENT_TIMESTAMP NULL,
	"TYPE" varchar(50) NULL,
	"From" int8 NULL,
	"To" int8 NULL,
	"AverageMilesPerHour" real NULL,
	CONSTRAINT PRIMARY KEY ("ID")
);

-- NORESPONSEREASONS
CREATE TABLE IF NOT EXISTS noresponsereasons (
	"ID" int8 generated by default as identity NOT NULL,
	"Title" varchar(500) NULL,
	"Description" varchar(500) NULL,
	CONSTRAINT PRIMARY KEY ("ID")
);

-- NOTIFICATIONS
CREATE TABLE IF NOT EXISTS notifications (
	"ID" int8 generated by default as identity NOT NULL,
	"CONFLICTID" int8 NULL,
	"ProviderID" uuid NULL,
	"AppProviderID" int8 NULL,
	"NotificationType" varchar(50) NULL,
	"CreatedDate" date NULL,
	"CreatedDateTime" timestamp NULL,
	"ReadUnreadFlag" int2 NULL,
	"Contract" varchar(100) NULL,
	CONSTRAINT  PRIMARY KEY ("ID")
);

-- PAYER_DASHBOARD_AGENCY_COUNT
CREATE TABLE payer_dashboard_agency_count (
	"PAYERID" uuid NULL,
	"VISITDATE" date NULL,
	"PROVIDERID" uuid NULL,
	"P_NAME" varchar(100) NULL,
	"TIN" varchar(100) NULL,
	"VISIT_KEY" varchar(100) NULL	
);
CREATE INDEX idx_payer_dashboard_agency_count_cluster ON payer_dashboard_agency_count USING btree ("VISITDATE","PAYERID","PROVIDERID","P_NAME","TIN","VISIT_KEY"  );

-- PAYER_DASHBOARD_AGENCY_IMPACT
CREATE TABLE payer_dashboard_agency_impact (
	"PAYERID" uuid NULL,
	"VISITDATE" date NULL,
	"PROVIDERID" uuid NULL,
	"P_NAME" varchar(100) NULL,
	"TIN" varchar(100) NULL,
	"CON_SP" real NULL,
	"CON_OP" real NULL,
	"CON_FP" real NULL
);
CREATE INDEX idx_payer_dashboard_agency_impact_cluster ON payer_dashboard_agency_impact USING btree ("VISITDATE","PAYERID","PROVIDERID","P_NAME","TIN");

-- PAYER_DASHBOARD_CAREGIVER_COUNT
CREATE TABLE payer_dashboard_caregiver_count (
	"PAYERID" uuid NULL,
	"VISITDATE" date NULL,
	"SSN" varchar(20) NULL,
	"C_NAME" varchar(100) NULL,
	"VISIT_KEY" varchar(100) NULL
);
CREATE INDEX idx_payer_dashboard_caregiver_count_cluster ON payer_dashboard_caregiver_count USING btree ("VISITDATE","PAYERID","SSN","C_NAME","VISIT_KEY"  );

CREATE TABLE payer_dashboard_caregiver_impact (
	"PAYERID" uuid NULL,
	"VISITDATE" date NULL,
	"SSN" varchar(20) NULL,
	"C_NAME" varchar(100) NULL,
	"CON_SP" real NULL,
	"CON_OP" real NULL,
	"CON_FP" real NULL
);
CREATE INDEX idx_payer_dashboard_caregiver_impact_cluster ON payer_dashboard_caregiver_impact USING btree ("VISITDATE","PAYERID","SSN","C_NAME");

-- PAYER_DASHBOARD_CON_TYP_COUNT
CREATE TABLE payer_dashboard_con_typ_count (
	"PAYERID" uuid NULL,
	"VISITDATE" date NULL,
	"CONTYPE" varchar(50) NULL,
	"CONTYPEDESC" varchar(100) NULL,
	"VISIT_KEY" varchar(100) NULL	
);
CREATE INDEX idx_payer_dashboard_con_typ_count_cluster ON payer_dashboard_con_typ_count USING btree ("VISITDATE","PAYERID","CONTYPE","CONTYPEDESC","VISIT_KEY"  );

-- PAYER_DASHBOARD_CON_TYP_IMPACT
CREATE TABLE payer_dashboard_con_typ_impact (
	"PAYERID" uuid NULL,
	"VISITDATE" date NULL,
	"CONTYPE" varchar(50) NULL,
	"CONTYPEDESC" varchar(100) NULL,
	"CON_SP" real NULL,
	"CON_OP" real NULL,
	"CON_FP" real NULL
);
CREATE INDEX idx_payer_dashboard_con_typ_impact_cluster ON payer_dashboard_con_typ_impact USING btree ("VISITDATE","PAYERID","CONTYPE","CONTYPEDESC" );

-- PAYER_DASHBOARD_PATIENT_COUNT
CREATE TABLE payer_dashboard_patient_count (
	"PAYERID" uuid NULL,
	"VISITDATE" date NULL,
	"PATIENTID" uuid NULL,
	"PFNAME" varchar(100) NULL,
	"PLNAME" varchar(100) NULL,
	"PNAME" varchar(100) NULL,
	"ADMISSIONID" varchar(100) NULL,
	"VISIT_KEY" varchar(100) NULL	
);
CREATE INDEX idx_payer_dashboard_patient_count_cluster ON payer_dashboard_patient_count USING btree ("VISITDATE","PAYERID","PATIENTID", "PFNAME","PLNAME","PNAME","ADMISSIONID","VISIT_KEY"  );

-- PAYER_DASHBOARD_PATIENT_IMPACT
CREATE TABLE payer_dashboard_patient_impact (
	"PAYERID" uuid NULL,
	"VISITDATE" date NULL,
	"PATIENTID" uuid NULL,
	"PFNAME" varchar(100) NULL,
	"PLNAME" varchar(100) NULL,
	"PNAME" varchar(100) NULL,
	"ADMISSIONID" varchar(100) NULL,
	"CON_SP" real NULL,
	"CON_OP" real NULL,
	"CON_FP" real NULL
);
CREATE INDEX idx_payer_dashboard_patient_impact_cluster ON payer_dashboard_patient_impact USING btree ("VISITDATE","PAYERID","PATIENTID", "PFNAME","PLNAME","PNAME","ADMISSIONID");

-- PAYER_DASHBOARD_PAYER_COUNT
CREATE TABLE payer_dashboard_payer_count (
	"PAYERID" uuid NULL,
	"VISITDATE" date NULL,
	"CONPAYERID" varchar(50) NULL,
	"PNAME" varchar(100) NULL,
	"VISIT_KEY" varchar(100) NULL	
);
CREATE INDEX idx_payer_dashboard_payer_count_cluster ON payer_dashboard_payer_count USING btree ("VISITDATE","PAYERID","CONPAYERID","PNAME", "VISIT_KEY"  );

-- PAYER_DASHBOARD_PAYER_IMPACT
CREATE TABLE payer_dashboard_payer_impact (
	"PAYERID" uuid NULL,
	"VISITDATE" date NULL,
	"CONPAYERID" varchar(50) NULL,
	"PNAME" varchar(100) NULL,
	"CON_SP" real NULL,
	"CON_OP" real NULL,
	"CON_FP" real NULL	
);
CREATE INDEX idx_payer_dashboard_payer_impact_cluster ON payer_dashboard_payer_impact USING btree ("VISITDATE","PAYERID","CONPAYERID","PNAME");

-- PAYER_DASHBOARD_PAYER_CHART_COUNT
CREATE TABLE payer_dashboard_payer_chart_count (
	"PAYERID" uuid NULL,
	"VISITDATE" date NULL,
	"CONPAYERID" uuid NULL,
	"PNAME" varchar(100) NULL,
	"STATUSFLAG" varchar(5) NULL,
	"COSTTYPE" varchar(20) NULL,
	"VISITTYPE" varchar(20) NULL,
	"VISIT_KEY" varchar(100) NULL	
);
CREATE INDEX idx_payer_dashboard_payer_chart_count_cluster ON payer_dashboard_payer_chart_count USING btree ("VISITDATE","PAYERID","CONPAYERID","PNAME", "STATUSFLAG","COSTTYPE","VISITTYPE","VISIT_KEY"  );

-- PAYER_DASHBOARD_PAYER_CHART_IMPACT
CREATE TABLE payer_dashboard_payer_chart_impact (
	"PAYERID" uuid NULL,
	"VISITDATE" date NULL,
	"CONPAYERID" uuid NULL,
	"PNAME" varchar(100) NULL,
	"STATUSFLAG" varchar(5) NULL,
	"COSTTYPE" varchar(20) NULL,
	"VISITTYPE" varchar(20) NULL,
	"CON_SP" real NULL,
	"CON_OP" real NULL,
	"CON_FP" real NULL	
);
CREATE INDEX idx_payer_dashboard_payer_chart_impact_cluster ON payer_dashboard_payer_chart_impact USING btree ("VISITDATE","PAYERID","CONPAYERID","PNAME", "STATUSFLAG","COSTTYPE","VISITTYPE"  );

-- PAYER_PROVIDER_REMINDERS
CREATE TABLE IF NOT EXISTS payer_provider_reminders (
	"ID" int8 generated by default as identity NOT NULL,
	"PayerID" uuid NULL,
	"AppPayerID" int8 NULL,
	"Contract" varchar(100) NULL,
	"ProviderID" uuid NULL,
	"AppProviderID" int8 NULL,
	"ProviderName" varchar(100) NULL,
	"CreatedDateTime" timestamp DEFAULT CURRENT_TIMESTAMP NULL,
	"NumberOfDays" int4 NULL,
	CONSTRAINT PRIMARY KEY ("ID")
);

-- PROVIDER_DASHBOARD_AGENCY
CREATE TABLE IF NOT EXISTS provider_dashboard_agency (
	"PROVIDERID" uuid NULL,
	"OFFICEID" uuid NULL,
	"CRDATEUNIQUE" date NULL,
	"CONPROVIDERID" uuid NULL,
	"CON_P_NAME" varchar(100) NULL,
	"CON_TIN" varchar(100) NULL,
	"CON_TO" int8 NULL,
	"CON_SP" real NULL,
	"CON_OP" real NULL,
	"CON_FP" real NULL
);
CREATE INDEX IF NOT EXISTS idx_provider_dashboard_agency_cluster ON provider_dashboard_agency USING btree("PROVIDERID", "OFFICEID", "CRDATEUNIQUE", "CONPROVIDERID", "CON_P_NAME", "CON_TIN");

-- PROVIDER_DASHBOARD_CAREGIVER
CREATE TABLE IF NOT EXISTS provider_dashboard_caregiver (
	"PROVIDERID" uuid NULL,
	"OFFICEID" uuid NULL,
	"CRDATEUNIQUE" date NULL,
	"CAREGIVERID" uuid NULL,
	"C_CODE" varchar(100) NULL,
	"C_NAME" varchar(100) NULL,
	"CON_TO" int4 NULL,
	"CON_SP" real NULL,
	"CON_OP" real NULL,
	"CON_FP" real NULL
);
CREATE INDEX IF NOT EXISTS idx_provider_dashboard_caregiver_cluster ON provider_dashboard_caregiver USING btree("PROVIDERID", "OFFICEID", "CRDATEUNIQUE", "CAREGIVERID", "C_CODE", "C_NAME");

-- PROVIDER_DASHBOARD_CON_TYP
CREATE TABLE IF NOT EXISTS provider_dashboard_con_typ (
	"PROVIDERID" uuid NULL,
	"OFFICEID" uuid NULL,
	"CRDATEUNIQUE" date NULL,
	"EX_ST_MATCH_TO" int4 NULL,
	"EX_ST_MATCH_SP" real NULL,
	"EX_ST_MATCH_OP" real NULL,
	"EX_ST_MATCH_FP" real NULL,
	"EX_VT_MATCH_TO" int4 NULL,
	"EX_VT_MATCH_SP" real NULL,
	"EX_VT_MATCH_OP" real NULL,
	"EX_VT_MATCH_FP" real NULL,
	"EX_ST_VT_MATCH_TO" int4 NULL,
	"EX_ST_VT_MATCH_SP" real NULL,
	"EX_ST_VT_MATCH_OP" real NULL,
	"EX_ST_VT_MATCH_FP" real NULL,
	"ST_OVR_TO" int4 NULL,
	"ST_OVR_SP" real NULL,
	"ST_OVR_OP" real NULL,
	"ST_OVR_FP" real NULL,
	"VT_OVR_TO" int4 NULL,
	"VT_OVR_SP" real NULL,
	"VT_OVR_OP" real NULL,
	"VT_OVR_FP" real NULL,
	"ST_VT_OVR_TO" int4 NULL,
	"ST_VT_OVR_SP" real NULL,
	"ST_VT_OVR_OP" real NULL,
	"ST_VT_OVR_FP" real NULL,
	"TD_TO" int4 NULL,
	"TD_SP" real NULL,
	"TD_OP" real NULL,
	"TD_FP" real NULL,
	"IN_TO" int4 NULL,
	"IN_SP" real NULL,
	"IN_OP" real NULL,
	"IN_FP" real NULL,
	"PT_TO" int4 NULL,
	"PT_SP" real NULL,
	"PT_OP" real NULL,
	"PT_FP" real NULL
);
CREATE INDEX IF NOT EXISTS idx_provider_dashboard_con_typ_cluster ON provider_dashboard_con_typ USING btree ("PROVIDERID", "OFFICEID", "CRDATEUNIQUE");

-- PROVIDER_DASHBOARD_PATIENT
CREATE TABLE IF NOT EXISTS provider_dashboard_patient (
	"PROVIDERID" uuid NULL,
	"OFFICEID" uuid NULL,
	"CRDATEUNIQUE" date NULL,
	"PATIENTID" uuid NULL,
	"PFNAME" varchar(100) NULL,
	"PLNAME" varchar(100) NULL,
	"PNAME" varchar(100) NULL,
	"CON_TO" int4 NULL,
	"CON_SP" real NULL,
	"CON_OP" real NULL,
	"CON_FP" real NULL
);
CREATE INDEX IF NOT EXISTS idx_provider_dashboard_patient_cluster ON provider_dashboard_patient USING btree ("PROVIDERID", "OFFICEID", "CRDATEUNIQUE", "PATIENTID", "PFNAME", "PLNAME", "PNAME");

-- PROVIDER_DASHBOARD_PAYER
CREATE TABLE IF NOT EXISTS provider_dashboard_payer (
	"PROVIDERID" uuid NULL,
	"OFFICEID" uuid NULL,
	"CRDATEUNIQUE" date NULL,
	"PAYERID" uuid NULL,
	"PNAME" varchar(100) NULL,
	"CON_TO" int4 NULL,
	"CON_SP" real NULL,
	"CON_OP" real NULL,
	"CON_FP" real NULL
);
CREATE INDEX IF NOT EXISTS idx_provider_dashboard_payer_cluster ON provider_dashboard_payer USING btree("PROVIDERID", "OFFICEID", "CRDATEUNIQUE", "PAYERID", "PNAME");

-- PROVIDER_DASHBOARD_TOP
CREATE TABLE IF NOT EXISTS provider_dashboard_top (
	"PROVIDERID" uuid NULL,
	"OFFICEID" uuid NULL,
	"TODAYTOTAL" int4 NULL,
	"TODAYSHIFTPRICE" real NULL,
	"TODAYOVERLAPPRICE" real NULL,
	"SEVENTOTAL" int4 NULL,
	"SEVENFINALPRICE" real NULL,
	"THIRTYTOTAL" int4 NULL,
	"THIRTYFINALPRICE" real NULL
);
CREATE INDEX IF NOT EXISTS idx_provider_dashboard_top_cluster ON provider_dashboard_top USING btree("PROVIDERID", "OFFICEID");

-- SETTINGS
CREATE TABLE IF NOT EXISTS settings (
	"ExtraDistance" int8 NULL,
	"ExtraDistancePer" real NULL,
	"NORESPONSELIMITTIME" int8 NULL,
	"ID" int8 DEFAULT 0 NOT NULL,
	"UpdateCronFlag" int2 NULL,
	"InsertCronFlag" int2 NULL,
	"ConflictIDFlag" int2 NULL,
	"GroupIDFlag" int2 NULL,
	"VisitHistoryFlag" int2 NULL,
	"LastLoadDate" timestamp NULL,
	"InProgressFlag" int8 NULL,
	CONSTRAINT PRIMARY KEY ("ID")
);

-- TASK_HISTORY_LIST
CREATE TABLE IF NOT EXISTS task_history_list (
	"ID" int8 generated by default as identity NOT NULL,
	"NAME" varchar(100),
	"UNNAME" varchar(100),
	"EMAILSENT" varchar(10),
	"CREATED_AT" timestamp DEFAULT CURRENT_TIMESTAMP,
	CONSTRAINT PRIMARY KEY ("ID")
);

-- TMP_BILLABLE_UPDATES
CREATE TABLE IF NOT EXISTS tmp_billable_updates (
	"ID" int8 NOT NULL,
	"BMF" int4 NOT NULL,
	"BUF" text NOT NULL,
	"BMO" int4 NOT NULL,
	"BUO" text NOT NULL,
	CONSTRAINT PRIMARY KEY ("ID")
);

-- STATE_DASHBOARD_AGENCY_COUNT
CREATE TABLE state_dashboard_agency_count (
	"PAYERID" uuid NULL,
	"PROVIDERID" uuid NULL,
	"VISITDATE" date NULL,
	"P_NAME" varchar(100) NULL,
	"STATUSFLAG" varchar(5) NULL,
	"COSTTYPE" varchar(20) NULL,
	"VISITTYPE" varchar(20) NULL,
	"COUNTY" varchar(100) NULL,
	"SERVICECODE" varchar(50) NULL,
	"VISIT_KEY" varchar(100) NULL
);
CREATE INDEX idx_state_dashboard_agency_count_cluster ON state_dashboard_agency_count USING btree ("VISITDATE","PAYERID","PROVIDERID","P_NAME","STATUSFLAG","COSTTYPE","VISITTYPE","COUNTY","SERVICECODE","VISIT_KEY"  );

-- STATE_DASHBOARD_AGENCY_IMPACT
CREATE TABLE state_dashboard_agency_impact (
	"PAYERID" uuid NULL,
	"PROVIDERID" uuid NULL,
	"VISITDATE" date NULL,
	"P_NAME" varchar(100) NULL,
	"STATUSFLAG" varchar(5) NULL,
	"COSTTYPE" varchar(20) NULL,
	"VISITTYPE" varchar(20) NULL,
	"COUNTY" varchar(100) NULL,
	"SERVICECODE" varchar(50) NULL,
	"CON_SP" real NULL,
	"CON_OP" real NULL,
	"CON_FP" real NULL
);
CREATE INDEX idx_state_dashboard_agency_impact_cluster ON state_dashboard_agency_impact USING btree ("VISITDATE","PAYERID","PROVIDERID","P_NAME","STATUSFLAG","COSTTYPE","VISITTYPE","COUNTY","SERVICECODE");


-- STATE_DASHBOARD_CAREGIVER_COUNT
CREATE TABLE state_dashboard_caregiver_count (
	"PAYERID" uuid NULL,
	"PROVIDERID" uuid NULL,
	"VISITDATE" date NULL,
	"SSN" varchar(20) NULL,
	"C_NAME" varchar(100) NULL,
	"STATUSFLAG" varchar(5) NULL,
	"COSTTYPE" varchar(20) NULL,
	"VISITTYPE" varchar(20) NULL,
	"COUNTY" varchar(100) NULL,
	"SERVICECODE" varchar(50) NULL,
	"VISIT_KEY" varchar(100) NULL
);
CREATE INDEX idx_state_dashboard_caregiver_count_cluster ON state_dashboard_caregiver_count USING btree ("VISITDATE","PAYERID","PROVIDERID","SSN" ,"C_NAME","STATUSFLAG","COSTTYPE","VISITTYPE","COUNTY","SERVICECODE","VISIT_KEY"  );

-- STATE_DASHBOARD_CAREGIVER_IMPACT
CREATE TABLE state_dashboard_caregiver_impact (
	"PAYERID" uuid NULL,
	"PROVIDERID" uuid NULL,
	"VISITDATE" date NULL,
	"SSN" varchar(20) NULL,
	"C_NAME" varchar(100) NULL,
	"STATUSFLAG" varchar(5) NULL,
	"COSTTYPE" varchar(20) NULL,
	"VISITTYPE" varchar(20) NULL,
	"COUNTY" varchar(100) NULL,
	"SERVICECODE" varchar(50) NULL,
	"CON_SP" real NULL,
	"CON_OP" real NULL,
	"CON_FP" real NULL
);
CREATE INDEX idx_state_dashboard_caregiver_impact_cluster ON state_dashboard_caregiver_impact USING btree ("VISITDATE","PAYERID","PROVIDERID","SSN" ,"C_NAME","STATUSFLAG","COSTTYPE","VISITTYPE","COUNTY","SERVICECODE");

-- STATE_DASHBOARD_CON_TYP_COUNT
CREATE TABLE state_dashboard_con_type_count (
	"PAYERID" uuid NULL,
	"PROVIDERID" uuid NULL,
	"VISITDATE" date NULL,
	"CONTYPE" varchar(50) NULL,
	"CONTYPEDESC" varchar(100) NULL,
	"STATUSFLAG" varchar(5) NULL,
	"COSTTYPE" varchar(20) NULL,
	"VISITTYPE" varchar(20) NULL,
	"COUNTY" varchar(100) NULL,
	"SERVICECODE" varchar(50) NULL,
	"VISIT_KEY" varchar(100) NULL
);
CREATE INDEX idx_state_dashboard_con_type_count_cluster ON state_dashboard_con_type_count USING btree ("VISITDATE","PAYERID","PROVIDERID","CONTYPE","CONTYPEDESC", "STATUSFLAG","COSTTYPE","VISITTYPE","COUNTY","SERVICECODE","VISIT_KEY"  );

-- STATE_DASHBOARD_CON_TYP_IMPACT
CREATE TABLE state_dashboard_con_type_impact (
	"PAYERID" uuid NULL,
	"PROVIDERID" uuid NULL,
	"VISITDATE" date NULL,
	"CONTYPE" varchar(50) NULL,
	"CONTYPEDESC" varchar(100) NULL,
	"STATUSFLAG" varchar(5) NULL,
	"COSTTYPE" varchar(20) NULL,
	"VISITTYPE" varchar(20) NULL,
	"COUNTY" varchar(100) NULL,
	"SERVICECODE" varchar(50) NULL,
	"CON_SP" real NULL,
	"CON_OP" real NULL,
	"CON_FP" real NULL
);
CREATE INDEX idx_state_dashboard_con_type_impact_cluster ON state_dashboard_con_type_impact USING btree ("VISITDATE","PAYERID","PROVIDERID","CONTYPE","CONTYPEDESC", "STATUSFLAG","COSTTYPE","VISITTYPE","COUNTY","SERVICECODE");

-- STATE_DASHBOARD_PATIENT_COUNT
CREATE TABLE state_dashboard_patient_count (
	"PAYERID" uuid NULL,
	"PROVIDERID" uuid NULL,
	"VISITDATE" date NULL,
	"PATIENTID" uuid NULL,
	"PNAME" varchar(100) NULL,
	"STATUSFLAG" varchar(5) NULL,
	"COSTTYPE" varchar(20) NULL,
	"VISITTYPE" varchar(20) NULL,
	"COUNTY" varchar(100) NULL,
	"SERVICECODE" varchar(50) NULL,
	"VISIT_KEY" varchar(100) NULL	
);
CREATE INDEX idx_state_dashboard_patient_count_cluster ON state_dashboard_patient_count USING btree ("VISITDATE","PAYERID","PROVIDERID","PATIENTID","PNAME", "STATUSFLAG","COSTTYPE","VISITTYPE","COUNTY","SERVICECODE","VISIT_KEY"  );

-- STATE_DASHBOARD_PATIENT_IMPACT
CREATE TABLE state_dashboard_patient_impact (
	"PAYERID" uuid NULL,
	"PROVIDERID" uuid NULL,
	"VISITDATE" date NULL,
	"PATIENTID" uuid NULL,
	"PNAME" varchar(100) NULL,
	"STATUSFLAG" varchar(5) NULL,
	"COSTTYPE" varchar(20) NULL,
	"VISITTYPE" varchar(20) NULL,
	"COUNTY" varchar(100) NULL,
	"SERVICECODE" varchar(50) NULL,
	"CON_SP" real NULL,
	"CON_OP" real NULL,
	"CON_FP" real NULL
);
CREATE INDEX idx_state_dashboard_patient_impact_cluster ON state_dashboard_patient_impact USING btree ("VISITDATE","PAYERID","PROVIDERID","PATIENTID","PNAME", "STATUSFLAG","COSTTYPE","VISITTYPE","COUNTY","SERVICECODE");

-- STATE_DASHBOARD_PAYER_COUNT
CREATE TABLE state_dashboard_payer_count (
	"PAYERID" uuid NULL,
	"PROVIDERID" uuid NULL,
	"VISITDATE" date NULL,
	"PNAME" varchar(100) NULL,
	"STATUSFLAG" varchar(5) NULL,
	"COSTTYPE" varchar(20) NULL,
	"VISITTYPE" varchar(20) NULL,
	"COUNTY" varchar(100) NULL,
	"SERVICECODE" varchar(50) NULL,
	"VISIT_KEY" varchar(100) NULL	
);
CREATE INDEX idx_state_dashboard_payer_count_cluster ON state_dashboard_payer_count USING btree ("VISITDATE","PAYERID","PROVIDERID","PNAME","STATUSFLAG","COSTTYPE","VISITTYPE","COUNTY","SERVICECODE","VISIT_KEY"  );

-- STATE_DASHBOARD_PAYER_IMPACT
CREATE TABLE state_dashboard_payer_impact (
	"PAYERID" uuid NULL,
	"PROVIDERID" uuid NULL,
	"VISITDATE" date NULL,
	"PNAME" varchar(100) NULL,
	"STATUSFLAG" varchar(5) NULL,
	"COSTTYPE" varchar(20) NULL,
	"VISITTYPE" varchar(20) NULL,
	"COUNTY" varchar(100) NULL,
	"SERVICECODE" varchar(50) NULL,
	"CON_SP" real NULL,
	"CON_OP" real NULL,
	"CON_FP" real NULL
);
CREATE INDEX idx_state_dashboard_payer_impact_cluster ON state_dashboard_payer_impact USING btree ("VISITDATE","PAYERID","PROVIDERID","PNAME","STATUSFLAG","COSTTYPE","VISITTYPE","COUNTY","SERVICECODE");


--PAYER_CONFLICT_SUMMARY_COUNT
CREATE TABLE payer_conflict_summary_count (
	"PAYERID" uuid NULL,
	"PROVIDERID" uuid NULL,
	"CONPAYERID" uuid NULL,
	"PROVIDER_NAME" varchar(100) NULL,
	"TIN" varchar(100) NULL,
	"CONTRACT" varchar(100) NULL,
	"PATIENT_FNAME" varchar(100) NULL,
	"PATIENT_LNAME" varchar(100) NULL,
	"ADMISSIONID" varchar(100) NULL,
	"CAREGIVER_NAME" varchar(100) NULL,
	"CONTYPE" varchar(50) NULL,
	"CONTYPEDESC" varchar(100) NULL,
	"VISITDATE" date NULL,
	"CRDATEUNIQUE" date NULL,
	"STATUSFLAG" varchar(5) NULL,
	"VISIT_KEY" varchar(100) NULL	
);
CREATE INDEX idx_payer_conflict_summary_count_cluster ON payer_conflict_summary_count USING btree ("PAYERID","PROVIDERID","PROVIDER_NAME","TIN","CONTRACT","PATIENT_FNAME","PATIENT_LNAME", "ADMISSIONID",
 "CAREGIVER_NAME", "CONTYPE","VISITDATE","CRDATEUNIQUE","STATUSFLAG","VISIT_KEY"  );

--PAYER_CONFLICT_SUMMARY_IMPACT
CREATE TABLE payer_conflict_summary_impact (
	"PAYERID" uuid NULL,
	"PROVIDERID" uuid NULL,
	"CONPAYERID" uuid NULL,
	"PROVIDER_NAME" varchar(100) NULL,
	"TIN" varchar(100) NULL,
	"CONTRACT" varchar(100) NULL,
	"PATIENT_FNAME" varchar(100) NULL,
	"PATIENT_LNAME" varchar(100) NULL,
	"ADMISSIONID" varchar(100) NULL,
	"CAREGIVER_NAME" varchar(100) NULL,
	"CONTYPE" varchar(50) NULL,
	"CONTYPEDESC" varchar(100) NULL,
	"VISITDATE" date NULL,
	"CRDATEUNIQUE" date NULL,
	"STATUSFLAG" varchar(5) NULL,
	"CON_SP" real NULL,
	"CON_OP" real NULL,
	"CON_FP" real NULL
		
);
CREATE INDEX idx_payer_conflict_summary_impact_cluster ON payer_conflict_summary_impact USING btree ("PAYERID","PROVIDERID","PROVIDER_NAME","TIN","CONTRACT","PATIENT_FNAME","PATIENT_LNAME", "ADMISSIONID",
 "CAREGIVER_NAME", "CONTYPE","VISITDATE","CRDATEUNIQUE","STATUSFLAG" );
