CREATE OR REPLACE PROCEDURE CONFLICTREPORT.PUBLIC.LOAD_PAYER_DASHBOARD_CHART_DATA()
RETURNS VARCHAR
LANGUAGE JAVASCRIPT
EXECUTE AS CALLER
AS '
	// Section 1: Truncate All Target Tables
    var SQL_TRUNCATE_CON_TYPE_COUNT = `TRUNCATE TABLE CONFLICTREPORT.PUBLIC.STATE_DASHBOARD_CON_TYPE_COUNT;`;
	var SQL_TRUNCATE_CON_TYPE_IMPACT = `TRUNCATE TABLE CONFLICTREPORT.PUBLIC.STATE_DASHBOARD_CON_TYPE_IMPACT;`;
	var SQL_TRUNCATE_AGENCY_COUNT = `TRUNCATE TABLE CONFLICTREPORT.PUBLIC.STATE_DASHBOARD_AGENCY_COUNT;`;
	var SQL_TRUNCATE_AGENCY_IMPACT = `TRUNCATE TABLE CONFLICTREPORT.PUBLIC.STATE_DASHBOARD_AGENCY_IMPACT;`;
	var SQL_TRUNCATE_PATIENT_COUNT = `TRUNCATE TABLE CONFLICTREPORT.PUBLIC.STATE_DASHBOARD_PATIENT_COUNT;`;
	var SQL_TRUNCATE_PATIENT_IMPACT = `TRUNCATE TABLE CONFLICTREPORT.PUBLIC.STATE_DASHBOARD_PATIENT_IMPACT;`;
	var SQL_TRUNCATE_PAYER_COUNT = `TRUNCATE TABLE CONFLICTREPORT.PUBLIC.STATE_DASHBOARD_PAYER_COUNT;`;
	var SQL_TRUNCATE_PAYER_IMPACT = `TRUNCATE TABLE CONFLICTREPORT.PUBLIC.STATE_DASHBOARD_PAYER_IMPACT;`;
	var SQL_TRUNCATE_CAREGIVER_COUNT= `TRUNCATE TABLE CONFLICTREPORT.PUBLIC.STATE_DASHBOARD_CAREGIVER_COUNT;`;
	var SQL_TRUNCATE_CAREGIVER_IMPACT = `TRUNCATE TABLE CONFLICTREPORT.PUBLIC.STATE_DASHBOARD_CAREGIVER_IMPACT;`;
	var SQL_TRUNCATE_PAYER_PAYER_COUNT = `TRUNCATE TABLE CONFLICTREPORT.PUBLIC.PAYER_DASHBOARD_PAYER_CHART_COUNT;`;
	var SQL_TRUNCATE_PAYER_PAYER_IMPACT = `TRUNCATE TABLE CONFLICTREPORT.PUBLIC.PAYER_DASHBOARD_PAYER_CHART_IMPACT;`;
	
	// Section 2: Load CON_TYPE_COUNT Data
    var SQL_INSERT_CON_TYPE_COUNT = `
		INSERT INTO CONFLICTREPORT.PUBLIC.STATE_DASHBOARD_CON_TYPE_COUNT (
			PAYERID, PROVIDERID, VISITDATE, CONTYPE, CONTYPEDESC, STATUSFLAG, COSTTYPE, VISITTYPE, COUNTY, SERVICECODE,
			VISIT_KEY
		)
		SELECT 
			"PayerID" AS PAYERID,
			"ProviderID" AS PROVIDERID,
			"VisitDate",
			CONTYPE,
			CASE 
				WHEN CONTYPE = ''only_to'' THEN ''Time Overlap Only''
				WHEN CONTYPE = ''only_td'' THEN ''Time Distance Only''
				WHEN CONTYPE = ''only_is'' THEN ''In Service Only''
				WHEN CONTYPE = ''both_to_td'' THEN ''Time Overlap and Time Distance''
				WHEN CONTYPE = ''both_to_is'' THEN ''Time Overlap and In Service''
				WHEN CONTYPE = ''both_td_is'' THEN ''Time Distance and In Service''
				WHEN CONTYPE = ''all_to_td_is'' THEN ''All Three (Time Overlap, Time Distance, and In Service)''
				ELSE NULL
			END AS CONTYPEDESC,
			"StatusFlag" AS STATUSFLAG,
			COSTTYPE,
			VISITTYPE,
			NULLIF(COUNTY, '''') AS COUNTY,
			"ServiceCode" AS SERVICECODE,
			VISIT_KEY,
		FROM CONFLICTREPORT.PUBLIC.DT_PAYER_CONFLICTS_COMMON
		GROUP BY 
			"PayerID",
			"ProviderID",
			"VisitDate",
			CONTYPE,
			"StatusFlag",
			COSTTYPE,
			VISITTYPE,
			NULLIF(COUNTY, ''''),
			"ServiceCode",
			VISIT_KEY;
    `;
	
	// Section 3: Load CON_TYPE_IMPACT Data
    var SQL_INSERT_CON_TYPE_IMPACT = `
		INSERT INTO CONFLICTREPORT.PUBLIC.STATE_DASHBOARD_CON_TYPE_IMPACT (
			PAYERID, PROVIDERID, VISITDATE, CONTYPE, CONTYPEDESC, STATUSFLAG, COSTTYPE, VISITTYPE, COUNTY, SERVICECODE,
			CON_SP, CON_OP, CON_FP
		)
		SELECT 
			"PayerID" AS PAYERID,
			"ProviderID" AS PROVIDERID,
			"VisitDate",
			CONTYPE,
			CASE 
				WHEN CONTYPE = ''only_to'' THEN ''Time Overlap Only''
				WHEN CONTYPE = ''only_td'' THEN ''Time Distance Only''
				WHEN CONTYPE = ''only_is'' THEN ''In Service Only''
				WHEN CONTYPE = ''both_to_td'' THEN ''Time Overlap and Time Distance''
				WHEN CONTYPE = ''both_to_is'' THEN ''Time Overlap and In Service''
				WHEN CONTYPE = ''both_td_is'' THEN ''Time Distance and In Service''
				WHEN CONTYPE = ''all_to_td_is'' THEN ''All Three (Time Overlap, Time Distance, and In Service)''
				ELSE NULL
			END AS CONTYPEDESC,
			"StatusFlag" AS STATUSFLAG,
			COSTTYPE,
			VISITTYPE,
			NULLIF(COUNTY, '''') AS COUNTY,
			"ServiceCode" AS SERVICECODE,
			SUM(FULL_SHIFT_AMOUNT) AS CON_SP,
			SUM(OVERLAP_AMOUNT) AS CON_OP,
			SUM(CASE WHEN "StatusFlag" = ''R'' THEN OVERLAP_AMOUNT ELSE 0 END) AS CON_FP
		FROM CONFLICTREPORT.PUBLIC.DT_PAYER_CONFLICTS_COMMON
		GROUP BY 
			"PayerID",
			"ProviderID",
			"VisitDate",
			CONTYPE,
			"StatusFlag",
			COSTTYPE,
			VISITTYPE,
			NULLIF(COUNTY, ''''),
			"ServiceCode";
    `;
	// Section 4: Load AGENCY_COUNT Data
    var SQL_INSERT_AGENCY_COUNT = `
		INSERT INTO CONFLICTREPORT.PUBLIC.STATE_DASHBOARD_AGENCY_COUNT (
			PAYERID, PROVIDERID, VISITDATE,P_NAME, STATUSFLAG, COSTTYPE, VISITTYPE, COUNTY, SERVICECODE,
			VISIT_KEY
		)
		SELECT 
			"PayerID" AS PAYERID,
			"ProviderID" AS PROVIDERID,
			"VisitDate",
			"ProviderName" AS P_NAME,
			"StatusFlag" AS STATUSFLAG,
			COSTTYPE,
			VISITTYPE,
			NULLIF(COUNTY, '''') AS COUNTY,
			"ServiceCode" AS SERVICECODE,
			VISIT_KEY,
		FROM CONFLICTREPORT.PUBLIC.DT_PAYER_CONFLICTS_COMMON
		WHERE "ProviderName" IS NOT NULL
		GROUP BY 
			"PayerID",
			"ProviderID",
			"ProviderName",
			"VisitDate",
			"StatusFlag",
			COSTTYPE,
			VISITTYPE,
			NULLIF(COUNTY, ''''),
			"ServiceCode",
			VISIT_KEY;
    `;
	// Section 5: Load AGENCY_IMPACT Data
    var SQL_INSERT_AGENCY_IMPACT = `
		INSERT INTO CONFLICTREPORT.PUBLIC.STATE_DASHBOARD_AGENCY_IMPACT (
			PAYERID, PROVIDERID, VISITDATE, P_NAME, STATUSFLAG, COSTTYPE, VISITTYPE, COUNTY, SERVICECODE,
			CON_SP, CON_OP, CON_FP
		)
		SELECT 
			"PayerID" AS PAYERID,
			"ProviderID" AS PROVIDERID,
			"VisitDate",
			"ProviderName" AS P_NAME,
			"StatusFlag" AS STATUSFLAG,
			COSTTYPE,
			VISITTYPE,
			NULLIF(COUNTY, '''') AS COUNTY,
			"ServiceCode" AS SERVICECODE,
			SUM(FULL_SHIFT_AMOUNT) AS CON_SP,
			SUM(OVERLAP_AMOUNT) AS CON_OP,
			SUM(CASE WHEN "StatusFlag" = ''R'' THEN OVERLAP_AMOUNT ELSE 0 END) AS CON_FP
		FROM CONFLICTREPORT.PUBLIC.DT_PAYER_CONFLICTS_COMMON
		WHERE "ProviderName" IS NOT NULL
		GROUP BY 
			"PayerID",
			"ProviderID",
			"ProviderName",
			"VisitDate",
			"StatusFlag",
			COSTTYPE,
			VISITTYPE,
			NULLIF(COUNTY, ''''),
			"ServiceCode";
    `;
	
	
	// Section 6: Load PATIENT_COUNT Data
    var SQL_INSERT_PATIENT_COUNT = `
		INSERT INTO CONFLICTREPORT.PUBLIC.STATE_DASHBOARD_PATIENT_COUNT (
			PAYERID, PROVIDERID, VISITDATE, PATIENTID, PNAME, STATUSFLAG, COSTTYPE, VISITTYPE, COUNTY, SERVICECODE,
			VISIT_KEY
		)
		SELECT 
			"PayerID" AS PAYERID,
			"ProviderID" AS PROVIDERID,
			"VisitDate",
			"PA_PatientID" AS PATIENTID, 
			"PA_PName" AS PNAME,
			"StatusFlag" AS STATUSFLAG,
			COSTTYPE,
			VISITTYPE,
			NULLIF(COUNTY, '''') AS COUNTY,
			"ServiceCode" AS SERVICECODE,
			VISIT_KEY,
		FROM CONFLICTREPORT.PUBLIC.DT_PAYER_CONFLICTS_COMMON
		WHERE  "PA_PName" IS NOT NULL 
		GROUP BY 
			"PayerID",
			"ProviderID",
			"VisitDate",
			"PA_PatientID",
			"PA_PName",
			"StatusFlag",
			COSTTYPE,
			VISITTYPE,
			NULLIF(COUNTY, ''''),
			"ServiceCode",
			VISIT_KEY;
    `;
	
	// Section 7: Load PATIENT_IMPACT Data
    var SQL_INSERT_PATIENT_IMPACT = `
		INSERT INTO CONFLICTREPORT.PUBLIC.STATE_DASHBOARD_PATIENT_IMPACT (
			PAYERID, PROVIDERID, VISITDATE, PATIENTID, PNAME, STATUSFLAG, COSTTYPE, VISITTYPE, COUNTY, SERVICECODE,
			CON_SP, CON_OP, CON_FP
		)
		SELECT 
			"PayerID" AS PAYERID,
			"ProviderID" AS PROVIDERID,
			"VisitDate",
			"PA_PatientID" AS PATIENTID, 
			"PA_PName" AS PNAME,
			"StatusFlag" AS STATUSFLAG,
			COSTTYPE,
			VISITTYPE,
			NULLIF(COUNTY, '''') AS COUNTY,
			"ServiceCode" AS SERVICECODE,
			SUM(FULL_SHIFT_AMOUNT) AS CON_SP,
			SUM(OVERLAP_AMOUNT) AS CON_OP,
			SUM(CASE WHEN "StatusFlag" = ''R'' THEN OVERLAP_AMOUNT ELSE 0 END) AS CON_FP
		FROM CONFLICTREPORT.PUBLIC.DT_PAYER_CONFLICTS_COMMON
		WHERE  "PA_PName" IS NOT NULL 
		GROUP BY 
			"PayerID",
			"ProviderID",
			"PA_PatientID",
			"PA_PName",
			"VisitDate",
			"StatusFlag",
			COSTTYPE,
			VISITTYPE,
			NULLIF(COUNTY, ''''),
			"ServiceCode";
    `;
	// Section 8: Load PAYER_COUNT Data
    var SQL_INSERT_PAYER_COUNT = `
		INSERT INTO CONFLICTREPORT.PUBLIC.STATE_DASHBOARD_PAYER_COUNT (
			PAYERID, PROVIDERID, VISITDATE,PNAME, STATUSFLAG, COSTTYPE, VISITTYPE, COUNTY, SERVICECODE,
			VISIT_KEY
		)
		SELECT 
			"PayerID" AS PAYERID,
			"ProviderID" AS PROVIDERID,
			"VisitDate",
			"Contract" AS PNAME,
			"StatusFlag" AS STATUSFLAG,
			COSTTYPE,
			VISITTYPE,
			NULLIF(COUNTY, '''') AS COUNTY,
			"ServiceCode" AS SERVICECODE,
			VISIT_KEY,
		FROM CONFLICTREPORT.PUBLIC.DT_PAYER_CONFLICTS_COMMON
		WHERE "Contract" IS NOT NULL
		GROUP BY 
			"PayerID",
			"ProviderID",
			"VisitDate",
			"Contract",
			"StatusFlag",
			COSTTYPE,
			VISITTYPE,
			NULLIF(COUNTY, ''''),
			"ServiceCode",
			VISIT_KEY;
    `;
	
	// Section 9: Load PAYER_IMPACT Data
    var SQL_INSERT_PAYER_IMPACT = `
		INSERT INTO CONFLICTREPORT.PUBLIC.STATE_DASHBOARD_PAYER_IMPACT (
			PAYERID, PROVIDERID, VISITDATE, PNAME, STATUSFLAG, COSTTYPE, VISITTYPE, COUNTY, SERVICECODE,
			CON_SP, CON_OP, CON_FP
		)
		SELECT 
			"PayerID" AS PAYERID,
			"ProviderID" AS PROVIDERID,
			"VisitDate",
			"Contract" AS PNAME,
			"StatusFlag" AS STATUSFLAG,
			COSTTYPE,
			VISITTYPE,
			NULLIF(COUNTY, '''') AS COUNTY,
			"ServiceCode" AS SERVICECODE,
			SUM(FULL_SHIFT_AMOUNT) AS CON_SP,
			SUM(OVERLAP_AMOUNT) AS CON_OP,
			SUM(CASE WHEN "StatusFlag" = ''R'' THEN OVERLAP_AMOUNT ELSE 0 END) AS CON_FP
		FROM CONFLICTREPORT.PUBLIC.DT_PAYER_CONFLICTS_COMMON
		WHERE "Contract" IS NOT NULL
		GROUP BY 
			"PayerID",
			"ProviderID",
			"Contract",
			"VisitDate",
			"StatusFlag",
			COSTTYPE,
			VISITTYPE,
			NULLIF(COUNTY, ''''),
			"ServiceCode";
    `;
	
	// Section 10: Load CAREGIVER_COUNT Data
    var SQL_INSERT_CAREGIVER_COUNT = `
		INSERT INTO CONFLICTREPORT.PUBLIC.STATE_DASHBOARD_CAREGIVER_COUNT (
			PAYERID, PROVIDERID, VISITDATE, SSN, C_NAME, STATUSFLAG, COSTTYPE, VISITTYPE, COUNTY, SERVICECODE,
			VISIT_KEY
		)
		SELECT 
			"PayerID" AS PAYERID,
			"ProviderID" AS PROVIDERID,
			"VisitDate",
			"SSN",
			MAX(CONCAT("AideFName",'' '', "AideLName")) AS C_NAME,
			"StatusFlag" AS STATUSFLAG,
			COSTTYPE,
			VISITTYPE,
			NULLIF(COUNTY, '''') AS COUNTY,
			"ServiceCode" AS SERVICECODE,
			VISIT_KEY,
		FROM CONFLICTREPORT.PUBLIC.DT_PAYER_CONFLICTS_COMMON
		WHERE  "SSN" IS NOT NULL
		GROUP BY 
			"PayerID",
			"ProviderID",
			"VisitDate",
			"SSN",
			"StatusFlag",
			COSTTYPE,
			VISITTYPE,
			NULLIF(COUNTY, ''''),
			"ServiceCode",
			VISIT_KEY;
    `;
	// Section 11: Load CAREGIVER_IMPACT Data
    var SQL_INSERT_CAREGIVER_IMPACT = `
		INSERT INTO CONFLICTREPORT.PUBLIC.STATE_DASHBOARD_CAREGIVER_IMPACT (
			PAYERID, PROVIDERID, VISITDATE, SSN, C_NAME, STATUSFLAG, COSTTYPE, VISITTYPE, COUNTY, SERVICECODE,
			CON_SP, CON_OP, CON_FP
		)
		SELECT 
			"PayerID" AS PAYERID,
			"ProviderID" AS PROVIDERID,
			"VisitDate",
			"SSN",
			MAX(CONCAT("AideFName",'' '', "AideLName")) AS C_NAME,
			"StatusFlag" AS STATUSFLAG,
			COSTTYPE,
			VISITTYPE,
			NULLIF(COUNTY, '''') AS COUNTY,
			"ServiceCode" AS SERVICECODE,
			SUM(FULL_SHIFT_AMOUNT) AS CON_SP,
			SUM(OVERLAP_AMOUNT) AS CON_OP,
			SUM(CASE WHEN "StatusFlag" = ''R'' THEN OVERLAP_AMOUNT ELSE 0 END) AS CON_FP
		FROM CONFLICTREPORT.PUBLIC.DT_PAYER_CONFLICTS_COMMON
		WHERE  "SSN" IS NOT NULL
		GROUP BY 
			"PayerID",
			"ProviderID",
			"VisitDate",
			"SSN",
			"StatusFlag",
			COSTTYPE,
			VISITTYPE,
			NULLIF(COUNTY, ''''),
			"ServiceCode";
    `;
	
	// Section 12: Load PAYER_PAYER_COUNT Data
	var SQL_INSERT_PAYER_PAYER_COUNT = `
		INSERT INTO CONFLICTREPORT.PUBLIC.PAYER_DASHBOARD_PAYER_CHART_COUNT (
			PAYERID, VISITDATE, CONPAYERID,PNAME, STATUSFLAG, COSTTYPE, VISITTYPE, 
			VISIT_KEY
		)
		SELECT 
			"PayerID" AS PAYERID,
			"VisitDate" AS VISITDATE,
			"ConPayerID" AS CONPAYERID,
			"ConContract" AS PNAME,
			"StatusFlag" AS STATUSFLAG,
			COSTTYPE,
			VISITTYPE,
			VISIT_KEY
		FROM CONFLICTREPORT.PUBLIC.DT_PAYER_CONFLICTS_COMMON
		WHERE "ConPayerID" != ''0'' AND "Contract" IS NOT NULL AND "ContractType" != ''Internal'' AND "ConContractType" != ''Internal''
		GROUP BY 
			"VisitDate",
			"PayerID",
			"ConPayerID",
			"ConContract",
			"StatusFlag",
			COSTTYPE,
			VISITTYPE,
			VISIT_KEY;
    `;
	// Section 9: Load PAYER__PAYER_IMPACT Data
    var SQL_INSERT_PAYER_PAYER_IMPACT = `
		INSERT INTO CONFLICTREPORT.PUBLIC.PAYER_DASHBOARD_PAYER_CHART_IMPACT (
			PAYERID,  VISITDATE,CONPAYERID, PNAME, STATUSFLAG, COSTTYPE, VISITTYPE,
			CON_SP, CON_OP, CON_FP
		)
		SELECT 
			"PayerID" AS PAYERID,
			"VisitDate"  AS VISITDATE,
			"ConPayerID" AS CONPAYERID,
			"ConContract"  AS PNAME,
			"StatusFlag" AS STATUSFLAG,
			COSTTYPE,
			VISITTYPE,
			SUM(FULL_SHIFT_AMOUNT) AS CON_SP,
			SUM(OVERLAP_AMOUNT) AS CON_OP,
			SUM(CASE WHEN "StatusFlag" = ''R'' THEN OVERLAP_AMOUNT ELSE 0 END) AS CON_FP
		FROM CONFLICTREPORT.PUBLIC.DT_PAYER_CONFLICTS_COMMON
		WHERE "ConPayerID" != ''0'' AND "Contract" IS NOT NULL AND "ContractType" != ''Internal'' AND "ConContractType" != ''Internal''
		GROUP BY 
			"VisitDate","PayerID","ConPayerID",
			"ConContract", "StatusFlag",COSTTYPE,
			VISITTYPE;
    `;
	


		
    try {
        // Execute all truncates first
        snowflake.execute({ sqlText: SQL_TRUNCATE_CON_TYPE_COUNT });
		snowflake.execute({ sqlText: SQL_TRUNCATE_CON_TYPE_IMPACT });
		snowflake.execute({ sqlText: SQL_TRUNCATE_AGENCY_COUNT });
		snowflake.execute({ sqlText: SQL_TRUNCATE_AGENCY_IMPACT });
		snowflake.execute({ sqlText: SQL_TRUNCATE_PATIENT_COUNT });
		snowflake.execute({ sqlText: SQL_TRUNCATE_PATIENT_IMPACT });
		snowflake.execute({ sqlText: SQL_TRUNCATE_PAYER_COUNT });
		snowflake.execute({ sqlText: SQL_TRUNCATE_PAYER_IMPACT });
		snowflake.execute({ sqlText: SQL_TRUNCATE_CAREGIVER_COUNT });
		snowflake.execute({ sqlText: SQL_TRUNCATE_CAREGIVER_IMPACT });
		snowflake.execute({ sqlText: SQL_TRUNCATE_PAYER_PAYER_COUNT });
		snowflake.execute({ sqlText: SQL_TRUNCATE_PAYER_PAYER_IMPACT });
		
        // Execute all inserts
        snowflake.execute({ sqlText: SQL_INSERT_CON_TYPE_COUNT });
		snowflake.execute({ sqlText: SQL_INSERT_CON_TYPE_IMPACT });
		snowflake.execute({ sqlText: SQL_INSERT_AGENCY_COUNT });
		snowflake.execute({ sqlText: SQL_INSERT_AGENCY_IMPACT });
		snowflake.execute({ sqlText: SQL_INSERT_PATIENT_COUNT });
		snowflake.execute({ sqlText: SQL_INSERT_PATIENT_IMPACT });
		snowflake.execute({ sqlText: SQL_INSERT_PAYER_COUNT });
		snowflake.execute({ sqlText: SQL_INSERT_PAYER_IMPACT });
		snowflake.execute({ sqlText: SQL_INSERT_CAREGIVER_COUNT });
		snowflake.execute({ sqlText: SQL_INSERT_CAREGIVER_IMPACT });
		snowflake.execute({ sqlText: SQL_INSERT_PAYER_PAYER_COUNT });
		snowflake.execute({ sqlText: SQL_INSERT_PAYER_PAYER_IMPACT });
		
		
        return "State Dashboard Data Loaded Successfully.";
    } catch (err) {
        throw "ERROR: " + err.message;
    }
';