-- ============================================================================
-- TASK_01 - STEP 03: Copy Data Chunk (ID Range)
-- ============================================================================
-- Chunked version for parallel processing
-- Processes a specific ID range: {start_id} to {end_id}
--
-- Idempotent: Uses INSERT ... ON CONFLICT DO NOTHING to allow safe re-runs
-- ============================================================================

INSERT INTO {conflict_schema}.conflictvisitmaps_temp (
    "ID", "CONFLICTID", "SSN",
    "ProviderID", "AppProviderID", "ProviderName", "FederalTaxNumber",
    "VisitID", "AppVisitID",
    "ConProviderID", "ConAppProviderID", "ConProviderName", "ConFederalTaxNumber",
    "ConVisitID", "ConAppVisitID",
    "VisitDate",
    "SchStartTime", "SchEndTime",
    "ConSchStartTime", "ConSchEndTime",
    "VisitStartTime", "VisitEndTime",
    "ConVisitStartTime", "ConVisitEndTime",
    "EVVStartTime", "EVVEndTime",
    "ConEVVStartTime", "ConEVVEndTime",
    "CaregiverID", "AppCaregiverID",
    "AideCode", "AideName", "AideSSN",
    "ConCaregiverID", "ConAppCaregiverID",
    "ConAideCode", "ConAideName", "ConAideSSN",
    "OfficeID", "AppOfficeID", "Office",
    "ConOfficeID", "ConAppOfficeID", "ConOffice",
    "PatientID", "AppPatientID", "PAdmissionID", "PName",
    "PAddressID", "PAppAddressID",
    "PAddressL1", "PAddressL2", "PCity",
    "PAddressState", "PZipCode", "PCounty",
    "PLongitude", "PLatitude",
    "ConPatientID", "ConAppPatientID", "ConPAdmissionID",
    "ConPName", "ConPAddressID", "ConPAppAddressID",
    "ConPAddressL1", "ConPAddressL2", "ConPCity",
    "ConPAddressState", "ConPZipCode", "ConPCounty",
    "ConPLongitude", "ConPLatitude",
    "PayerID", "AppPayerID", "Contract",
    "ConPayerID", "ConAppPayerID", "ConContract",
    "BilledDate", "ConBilledDate",
    "BilledHours", "ConBilledHours",
    "Billed", "ConBilled",
    "MinuteDiffBetweenSch",
    "DistanceMilesFromLatLng",
    "AverageMilesPerHour",
    "ETATravelMinutes",
    "InserviceStartDate", "InserviceEndDate",
    "PTOStartDate", "PTOEndDate",
    "ConInserviceStartDate", "ConInserviceEndDate",
    "ConPTOStartDate", "ConPTOEndDate",
    "ServiceCodeID", "AppServiceCodeID",
    "RateType", "ServiceCode",
    "ConServiceCodeID", "ConAppServiceCodeID",
    "ConRateType", "ConServiceCode",
    "SameSchTimeFlag", "SameVisitTimeFlag",
    "SchAndVisitTimeSameFlag",
    "SchOverAnotherSchTimeFlag",
    "VisitTimeOverAnotherVisitTimeFlag",
    "SchTimeOverVisitTimeFlag",
    "DistanceFlag", "InServiceFlag", "PTOFlag",
    "StatusFlag",
    "ConStatusFlag",
    "AideFName", "AideLName",
    "ConAideFName", "ConAideLName",
    "PFName", "PLName",
    "ConPFName", "ConPLName",
    "PMedicaidNumber", "ConPMedicaidNumber"
)
SELECT 
    CVM."ID", CVM."CONFLICTID", CVM."SSN",
    CVM."ProviderID", CVM."AppProviderID", CVM."ProviderName", CVM."FederalTaxNumber",
    CVM."VisitID", CVM."AppVisitID",
    CVM."ConProviderID", CVM."ConAppProviderID", CVM."ConProviderName", CVM."ConFederalTaxNumber",
    CVM."ConVisitID", CVM."ConAppVisitID",
    CVM."VisitDate",
    CVM."SchStartTime", CVM."SchEndTime",
    CVM."ConSchStartTime", CVM."ConSchEndTime",
    CVM."VisitStartTime", CVM."VisitEndTime",
    CVM."ConVisitStartTime", CVM."ConVisitEndTime",
    CVM."EVVStartTime", CVM."EVVEndTime",
    CVM."ConEVVStartTime", CVM."ConEVVEndTime",
    CVM."CaregiverID", CVM."AppCaregiverID",
    CVM."AideCode", CVM."AideName", CVM."AideSSN",
    CVM."ConCaregiverID", CVM."ConAppCaregiverID",
    CVM."ConAideCode", CVM."ConAideName", CVM."ConAideSSN",
    CVM."OfficeID", CVM."AppOfficeID", CVM."Office",
    CVM."ConOfficeID", CVM."ConAppOfficeID", CVM."ConOffice",
    CVM."PatientID", CVM."AppPatientID", CVM."PAdmissionID", CVM."PName",
    CVM."PAddressID", CVM."PAppAddressID",
    CVM."PAddressL1", CVM."PAddressL2", CVM."PCity",
    CVM."PAddressState", CVM."PZipCode", CVM."PCounty",
    CVM."PLongitude", CVM."PLatitude",
    CVM."ConPatientID", CVM."ConAppPatientID", CVM."ConPAdmissionID",
    CVM."ConPName", CVM."ConPAddressID", CVM."ConPAppAddressID",
    CVM."ConPAddressL1", CVM."ConPAddressL2", CVM."ConPCity",
    CVM."ConPAddressState", CVM."ConPZipCode", CVM."ConPCounty",
    CVM."ConPLongitude", CVM."ConPLatitude",
    CVM."PayerID", CVM."AppPayerID", CVM."Contract",
    CVM."ConPayerID", CVM."ConAppPayerID", CVM."ConContract",
    CVM."BilledDate", CVM."ConBilledDate",
    CVM."BilledHours", CVM."ConBilledHours",
    CVM."Billed", CVM."ConBilled",
    CVM."MinuteDiffBetweenSch",
    CVM."DistanceMilesFromLatLng",
    CVM."AverageMilesPerHour",
    CVM."ETATravelMinutes",
    CVM."InserviceStartDate", CVM."InserviceEndDate",
    CVM."PTOStartDate", CVM."PTOEndDate",
    CVM."ConInserviceStartDate", CVM."ConInserviceEndDate",
    CVM."ConPTOStartDate", CVM."ConPTOEndDate",
    CVM."ServiceCodeID", CVM."AppServiceCodeID",
    CVM."RateType", CVM."ServiceCode",
    CVM."ConServiceCodeID", CVM."ConAppServiceCodeID",
    CVM."ConRateType", CVM."ConServiceCode",
    CVM."SameSchTimeFlag", CVM."SameVisitTimeFlag",
    CVM."SchAndVisitTimeSameFlag",
    CVM."SchOverAnotherSchTimeFlag",
    CVM."VisitTimeOverAnotherVisitTimeFlag",
    CVM."SchTimeOverVisitTimeFlag",
    CVM."DistanceFlag", CVM."InServiceFlag", CVM."PTOFlag",
    C."StatusFlag",
    CVM."StatusFlag" AS "ConStatusFlag",
    CVM."AideFName", CVM."AideLName",
    CVM."ConAideFName", CVM."ConAideLName",
    CVM."PFName", CVM."PLName",
    CVM."ConPFName", CVM."ConPLName",
    CVM."PMedicaidNumber", CVM."ConPMedicaidNumber"
FROM {conflict_schema}.conflictvisitmaps AS CVM
INNER JOIN {conflict_schema}.conflicts AS C 
    ON C."CONFLICTID" = CVM."CONFLICTID"
WHERE CVM."ID" BETWEEN {start_id} AND {end_id}
  AND CVM."VisitDate" BETWEEN 
    (CURRENT_DATE - INTERVAL '2 years') 
    AND (CURRENT_DATE + INTERVAL '45 days');
