-- =====================================================================
-- SNOWFLAKE SOURCE TABLE COUNTS (with filters applied)
-- =====================================================================
-- Run this in Snowflake to get source record counts
-- Copy results to Excel/spreadsheet for comparison
-- =====================================================================

SELECT 'ANALYTICS' AS sf_source_name, 'DIMPAYER' AS sf_source_name, COUNT(*) AS sf_record_count
FROM ANALYTICS.BI.DIMPAYER
WHERE "Is Active" = TRUE AND "Is Demo" = FALSE AND "Source System" = 'hha'

UNION ALL

SELECT 'ANALYTICS', 'DIMPROVIDER', COUNT(*)
FROM ANALYTICS.BI.DIMPROVIDER
WHERE "Is Active" = TRUE AND "Is Demo" = FALSE AND "Source System" = 'hha'

UNION ALL

SELECT 'ANALYTICS', 'DIMOFFICE', COUNT(*)
FROM ANALYTICS.BI.DIMOFFICE
WHERE "Is Active" = TRUE AND "Source System" = 'hha'

UNION ALL

SELECT 'ANALYTICS', 'DIMCONTRACT', COUNT(*)
FROM ANALYTICS.BI.DIMCONTRACT
WHERE "Is Active" = TRUE AND "Source System" = 'hha'

UNION ALL

SELECT 'ANALYTICS', 'DIMPAYERPROVIDER', COUNT(*)
FROM ANALYTICS.BI.DIMPAYERPROVIDER
WHERE "Source System" = 'hha'

UNION ALL

SELECT 'ANALYTICS', 'DIMUSER', COUNT(*)
FROM ANALYTICS.BI.DIMUSER
WHERE "Source System" = 'hha' AND "Is Support User" = FALSE AND "Username" IS NOT NULL

UNION ALL

SELECT 'ANALYTICS', 'DIMUSEROFFICES', COUNT(*)
FROM ANALYTICS.BI.DIMUSEROFFICES
WHERE "Source System" = 'hha' AND "Office Id" IS NOT NULL

UNION ALL

SELECT 'ANALYTICS', 'DIMPATIENT', COUNT(*)
FROM ANALYTICS.BI.DIMPATIENT
WHERE "Has Visit" = TRUE AND "Status" = 'Active' AND "Source System" = 'hha'

UNION ALL

SELECT 'ANALYTICS', 'DIMSERVICECODE', COUNT(*)
FROM ANALYTICS.BI.DIMSERVICECODE
WHERE "Source System" = 'hha' AND "Is Active" = TRUE

UNION ALL

SELECT 'ANALYTICS', 'DIMCAREGIVER', COUNT(*)
FROM ANALYTICS.BI.DIMCAREGIVER
WHERE "Source System" = 'hha'

UNION ALL

SELECT 'ANALYTICS', 'FACTCAREGIVERABSENCE', COUNT(*)
FROM ANALYTICS.BI.FACTCAREGIVERABSENCE
WHERE "Active" = TRUE AND "Source System" = 'hha'

UNION ALL

SELECT 'ANALYTICS', 'DIMPATIENTADDRESS', COUNT(*)
FROM ANALYTICS.BI.DIMPATIENTADDRESS
WHERE "Source System" = 'hha'

UNION ALL

SELECT 'ANALYTICS', 'FACTCAREGIVERINSERVICE', COUNT(*)
FROM ANALYTICS.BI.FACTCAREGIVERINSERVICE
WHERE "Source System" = 'hha'

UNION ALL

SELECT 'ANALYTICS', 'FACTVISITCALLPERFORMANCE_DELETED_CR', COUNT(*)
FROM ANALYTICS.BI.FACTVISITCALLPERFORMANCE_DELETED_CR
WHERE "External Source" = 'HHAX' AND "Permanent Deleted" = TRUE

UNION ALL

SELECT 'ANALYTICS', 'FACTVISITCALLPERFORMANCE_CR', COUNT(*)
FROM ANALYTICS.BI.FACTVISITCALLPERFORMANCE_CR
WHERE "External Source" = 'HHAX' AND "Permanent Deleted" = FALSE

UNION ALL

SELECT 'AGGREGATOR', 'multipayer_payer', COUNT(*)
FROM AGGNYPROD.PUBLIC."multipayer_payer"

UNION ALL

SELECT 'CONFLICT', 'SETTINGS', COUNT(*)
FROM CONFLICTREPORT.PUBLIC.SETTINGS

UNION ALL

SELECT 'CONFLICT', 'MPH', COUNT(*)
FROM CONFLICTREPORT.PUBLIC.MPH

UNION ALL

SELECT 'CONFLICT', 'LOG_FIELDS', COUNT(*)
FROM CONFLICTREPORT.PUBLIC.LOG_FIELDS

UNION ALL

SELECT 'CONFLICT', 'PROVIDER_DASHBOARD_TOP', COUNT(*)
FROM CONFLICTREPORT.PUBLIC.PROVIDER_DASHBOARD_TOP

UNION ALL

SELECT 'CONFLICT', 'PROVIDER_DASHBOARD_CON_TYP', COUNT(*)
FROM CONFLICTREPORT.PUBLIC.PROVIDER_DASHBOARD_CON_TYP

UNION ALL

SELECT 'CONFLICT', 'PROVIDER_DASHBOARD_PAYER', COUNT(*)
FROM CONFLICTREPORT.PUBLIC.PROVIDER_DASHBOARD_PAYER

UNION ALL

SELECT 'CONFLICT', 'PROVIDER_DASHBOARD_AGENCY', COUNT(*)
FROM CONFLICTREPORT.PUBLIC.PROVIDER_DASHBOARD_AGENCY

UNION ALL

SELECT 'CONFLICT', 'PROVIDER_DASHBOARD_PATIENT', COUNT(*)
FROM CONFLICTREPORT.PUBLIC.PROVIDER_DASHBOARD_PATIENT

UNION ALL

SELECT 'CONFLICT', 'PROVIDER_DASHBOARD_CAREGIVER', COUNT(*)
FROM CONFLICTREPORT.PUBLIC.PROVIDER_DASHBOARD_CAREGIVER

UNION ALL

SELECT 'CONFLICT', 'PAYER_DASHBOARD_CON_TYP_COUNT', COUNT(*)
FROM CONFLICTREPORT.PUBLIC.PAYER_DASHBOARD_CON_TYP_COUNT

UNION ALL

SELECT 'CONFLICT', 'PAYER_DASHBOARD_AGENCY_IMPACT', COUNT(*)
FROM CONFLICTREPORT.PUBLIC.PAYER_DASHBOARD_AGENCY_IMPACT

UNION ALL

SELECT 'CONFLICT', 'PAYER_DASHBOARD_PAYER_COUNT', COUNT(*)
FROM CONFLICTREPORT.PUBLIC.PAYER_DASHBOARD_PAYER_COUNT

UNION ALL

SELECT 'CONFLICT', 'PAYER_DASHBOARD_PAYER_CHART_COUNT', COUNT(*)
FROM CONFLICTREPORT.PUBLIC.PAYER_DASHBOARD_PAYER_CHART_COUNT

UNION ALL

SELECT 'CONFLICT', 'PAYER_DASHBOARD_PAYER_CHART_IMPACT', COUNT(*)
FROM CONFLICTREPORT.PUBLIC.PAYER_DASHBOARD_PAYER_CHART_IMPACT

UNION ALL

SELECT 'CONFLICT', 'PAYER_DASHBOARD_CAREGIVER_IMPACT', COUNT(*)
FROM CONFLICTREPORT.PUBLIC.PAYER_DASHBOARD_CAREGIVER_IMPACT

UNION ALL

SELECT 'CONFLICT', 'PAYER_DASHBOARD_PATIENT_IMPACT', COUNT(*)
FROM CONFLICTREPORT.PUBLIC.PAYER_DASHBOARD_PATIENT_IMPACT

UNION ALL

SELECT 'CONFLICT', 'PAYER_DASHBOARD_CAREGIVER_COUNT', COUNT(*)
FROM CONFLICTREPORT.PUBLIC.PAYER_DASHBOARD_CAREGIVER_COUNT

UNION ALL

SELECT 'CONFLICT', 'PAYER_DASHBOARD_PATIENT_COUNT', COUNT(*)
FROM CONFLICTREPORT.PUBLIC.PAYER_DASHBOARD_PATIENT_COUNT

UNION ALL

SELECT 'CONFLICT', 'PAYER_DASHBOARD_AGENCY_COUNT', COUNT(*)
FROM CONFLICTREPORT.PUBLIC.PAYER_DASHBOARD_AGENCY_COUNT

UNION ALL

SELECT 'CONFLICT', 'PAYER_DASHBOARD_PAYER_IMPACT', COUNT(*)
FROM CONFLICTREPORT.PUBLIC.PAYER_DASHBOARD_PAYER_IMPACT

UNION ALL

SELECT 'CONFLICT', 'STATE_DASHBOARD_AGENCY_IMPACT', COUNT(*)
FROM CONFLICTREPORT.PUBLIC.STATE_DASHBOARD_AGENCY_IMPACT

UNION ALL

SELECT 'CONFLICT', 'STATE_DASHBOARD_PAYER_IMPACT', COUNT(*)
FROM CONFLICTREPORT.PUBLIC.STATE_DASHBOARD_PAYER_IMPACT

UNION ALL

SELECT 'CONFLICT', 'STATE_DASHBOARD_CON_TYPE_IMPACT', COUNT(*)
FROM CONFLICTREPORT.PUBLIC.STATE_DASHBOARD_CON_TYPE_IMPACT

UNION ALL

SELECT 'CONFLICT', 'STATE_DASHBOARD_PATIENT_IMPACT', COUNT(*)
FROM CONFLICTREPORT.PUBLIC.STATE_DASHBOARD_PATIENT_IMPACT

UNION ALL

SELECT 'CONFLICT', 'PAYER_CONFLICT_SUMMARY_IMPACT', COUNT(*)
FROM CONFLICTREPORT.PUBLIC.PAYER_CONFLICT_SUMMARY_IMPACT

UNION ALL

SELECT 'CONFLICT', 'STATE_DASHBOARD_CAREGIVER_IMPACT', COUNT(*)
FROM CONFLICTREPORT.PUBLIC.STATE_DASHBOARD_CAREGIVER_IMPACT

UNION ALL

SELECT 'CONFLICT', 'PAYER_CONFLICT_SUMMARY_COUNT', COUNT(*)
FROM CONFLICTREPORT.PUBLIC.PAYER_CONFLICT_SUMMARY_COUNT

UNION ALL

SELECT 'CONFLICT', 'STATE_DASHBOARD_PATIENT_COUNT', COUNT(*)
FROM CONFLICTREPORT.PUBLIC.STATE_DASHBOARD_PATIENT_COUNT

UNION ALL

SELECT 'CONFLICT', 'STATE_DASHBOARD_PAYER_COUNT', COUNT(*)
FROM CONFLICTREPORT.PUBLIC.STATE_DASHBOARD_PAYER_COUNT

UNION ALL

SELECT 'CONFLICT', 'STATE_DASHBOARD_AGENCY_COUNT', COUNT(*)
FROM CONFLICTREPORT.PUBLIC.STATE_DASHBOARD_AGENCY_COUNT

UNION ALL

SELECT 'CONFLICT', 'STATE_DASHBOARD_CON_TYPE_COUNT', COUNT(*)
FROM CONFLICTREPORT.PUBLIC.STATE_DASHBOARD_CON_TYPE_COUNT

UNION ALL

SELECT 'CONFLICT', 'STATE_DASHBOARD_CAREGIVER_COUNT', COUNT(*)
FROM CONFLICTREPORT.PUBLIC.STATE_DASHBOARD_CAREGIVER_COUNT

UNION ALL

SELECT 'CONFLICT', 'FAILED_API_LOGS', COUNT(*)
FROM CONFLICTREPORT.PUBLIC.FAILED_API_LOGS

UNION ALL

SELECT 'CONFLICT', 'CONFLICTS', COUNT(*)
FROM CONFLICTREPORT.PUBLIC.CONFLICTS

UNION ALL

SELECT 'CONFLICT', 'CONFLICTVISITMAPS', COUNT(*)
FROM CONFLICTREPORT.PUBLIC.CONFLICTVISITMAPS

UNION ALL

SELECT 'CONFLICT', 'LOG_HISTORY', COUNT(*)
FROM CONFLICTREPORT.PUBLIC.LOG_HISTORY

UNION ALL

SELECT 'CONFLICT', 'LOG_HISTORY_VALUES', COUNT(*)
FROM CONFLICTREPORT.PUBLIC.LOG_HISTORY_VALUES

ORDER BY sf_source_name, pg_source_name;
