-- ============================================================================
-- Task 02.01 InService: Step 3 - Final InService Conflict Pairs (UNION ALL)
-- ============================================================================
--
-- PURPOSE: Produce InService conflict pairs in both directions:
--   Direction 1: Visit (V1) vs InService event (V2)
--   Direction 2: InService event (V1) vs Visit (V2)
--
-- Join conditions (matching old SP TASK_02/TASK_03):
--   - Same SSN (same caregiver)
--   - Different provider (cross-provider only)
--   - Temporal overlap: visit time range overlaps inservice date range
--
-- InService-specific behaviour:
--   - All 7 conflict flags = 'N' (no schedule/distance computation)
--   - Distance/travel columns = NULL
--   - InserviceStartDate/EndDate populated on the InService side, NULL on visit
--
-- No format placeholders required — uses the temp tables created in steps 1+2.
-- ============================================================================

-- ──────────────────────────────────────────────────────────────────────────
-- Direction 1: Visit (primary) vs InService event (conflicting)
-- ──────────────────────────────────────────────────────────────────────────
SELECT
  DISTINCT
  -- identifiers
  CAST(NULL AS STRING) AS "CONFLICTID",
  V1."SSN",
  -- visit 1 (primary = regular visit)
  V1."ProviderID",
  V1."AppProviderID",
  V1."ProviderName",
  V1."VisitID",
  V1."AppVisitID",
  -- visit 2 (conflicting = InService event)
  V2."ProviderID"  AS "ConProviderID",
  V2."AppProviderID" AS "ConAppProviderID",
  V2."ProviderName"  AS "ConProviderName",
  V2."VisitID"      AS "ConVisitID",
  V2."AppVisitID"   AS "ConAppVisitID",
  -- dates / times
  V1."VisitDate",
  V1."SchStartTime",
  V1."SchEndTime",
  V2."SchStartTime"  AS "ConSchStartTime",
  V2."SchEndTime"    AS "ConSchEndTime",
  V1."VisitStartTime",
  V1."VisitEndTime",
  V2."VisitStartTime" AS "ConVisitStartTime",
  V2."VisitEndTime"   AS "ConVisitEndTime",
  V1."EVVStartTime",
  V1."EVVEndTime",
  V2."EVVStartTime"  AS "ConEVVStartTime",
  V2."EVVEndTime"    AS "ConEVVEndTime",
  -- caregiver
  V1."CaregiverID",
  V1."AppCaregiverID",
  V1."AideCode",
  V1."AideName",
  V1."AideFName",
  V1."AideLName",
  V1."AideSSN",
  V1."AideStatus",
  V2."CaregiverID"  AS "ConCaregiverID",
  V2."AppCaregiverID" AS "ConAppCaregiverID",
  V2."AideCode"     AS "ConAideCode",
  V2."AideName"     AS "ConAideName",
  V2."AideFName"    AS "ConAideFName",
  V2."AideLName"    AS "ConAideLName",
  V2."AideSSN"      AS "ConAideSSN",
  V2."AideStatus"   AS "ConAideStatus",
  -- office
  V1."OfficeID",
  V1."AppOfficeID",
  V1."Office",
  V2."OfficeID"    AS "ConOfficeID",
  V2."AppOfficeID" AS "ConAppOfficeID",
  V2."Office"      AS "ConOffice",
  -- patient (visit side populated, InService side mostly NULL)
  V1."PatientID",
  V1."AppPatientID",
  V1."PAdmissionID",
  V1."PName",
  V1."PFName",
  V1."PLName",
  V1."PMedicaidNumber",
  V1."PStatus",
  V1."PAddressID",
  V1."PAppAddressID",
  V1."PAddressL1",
  V1."PAddressL2",
  V1."PCity",
  V1."PAddressState",
  V1."PZipCode",
  V1."PCounty",
  V1."Longitude" AS "PLongitude",
  V1."Latitude"  AS "PLatitude",
  -- conflict patient
  V2."PatientID"    AS "ConPatientID",
  V2."AppPatientID" AS "ConAppPatientID",
  V2."PAdmissionID" AS "ConPAdmissionID",
  V2."PName"        AS "ConPName",
  V2."PFName"       AS "ConPFName",
  V2."PLName"       AS "ConPLName",
  V2."PMedicaidNumber" AS "ConPMedicaidNumber",
  V2."PStatus"      AS "ConPStatus",
  V2."PAddressID"   AS "ConPAddressID",
  V2."PAppAddressID" AS "ConPAppAddressID",
  V2."PAddressL1"   AS "ConPAddressL1",
  V2."PAddressL2"   AS "ConPAddressL2",
  V2."PCity"        AS "ConPCity",
  V2."PAddressState" AS "ConPAddressState",
  V2."PZipCode"     AS "ConPZipCode",
  V2."PCounty"      AS "ConPCounty",
  V2."Longitude"    AS "ConPLongitude",
  V2."Latitude"     AS "ConPLatitude",
  -- payer
  V1."PayerID",
  V1."AppPayerID",
  V1."Contract",
  V1."PayerState",
  V2."PayerID"    AS "ConPayerID",
  V2."AppPayerID" AS "ConAppPayerID",
  V2."Contract"   AS "ConContract",
  V2."PayerState" AS "ConPayerState",
  -- billing
  V1."BilledDate",
  V2."BilledDate"    AS "ConBilledDate",
  V1."BilledHours",
  V2."BilledHours"   AS "ConBilledHours",
  V1."Billed",
  V2."Billed"        AS "ConBilled",
  V1."BilledRate",
  V1."TotalBilledAmount",
  V1."BillRateNonBilled",
  V1."BillRateBoth",
  V2."BilledRate"         AS "ConBilledRate",
  V2."TotalBilledAmount"  AS "ConTotalBilledAmount",
  V2."BillRateNonBilled"  AS "ConBillRateNonBilled",
  V2."BillRateBoth"       AS "ConBillRateBoth",
  -- distance / travel: always NULL for InService conflicts
  CAST(NULL AS NUMBER) AS "MinuteDiffBetweenSch",
  CAST(NULL AS NUMBER) AS "DistanceMilesFromLatLng",
  CAST(NULL AS NUMBER) AS "AverageMilesPerHour",
  CAST(NULL AS NUMBER) AS "ETATravleMinutes",
  -- service code
  V1."ServiceCodeID",
  V1."AppServiceCodeID",
  V1."RateType",
  V1."ServiceCode",
  V2."ServiceCodeID"    AS "ConServiceCodeID",
  V2."AppServiceCodeID" AS "ConAppServiceCodeID",
  V2."RateType"         AS "ConRateType",
  V2."ServiceCode"      AS "ConServiceCode",
  -- conflict flags: all 'N' for InService
  'N' AS "SameSchTimeFlag",
  'N' AS "SameVisitTimeFlag",
  'N' AS "SchAndVisitTimeSameFlag",
  'N' AS "SchOverAnotherSchTimeFlag",
  'N' AS "VisitTimeOverAnotherVisitTimeFlag",
  'N' AS "SchTimeOverVisitTimeFlag",
  'N' AS "DistanceFlag",
  -- missed / EVV
  V1."IsMissed",
  V1."MissedVisitReason",
  V1."EVVType",
  V2."IsMissed"         AS "ConIsMissed",
  V2."MissedVisitReason" AS "ConMissedVisitReason",
  V2."EVVType"          AS "ConEVVType",
  -- agency contact
  V1."AgencyContact",
  V2."AgencyContact"  AS "ConAgencyContact",
  V1."AgencyPhone",
  V2."AgencyPhone"    AS "ConAgencyPhone",
  -- last updated
  V1."LastUpdatedBy",
  V2."LastUpdatedBy"   AS "ConLastUpdatedBy",
  V1."LastUpdatedDate",
  V2."LastUpdatedDate" AS "ConLastUpdatedDate",
  -- contract type
  V1."ContractType",
  V2."ContractType"  AS "ConContractType",
  -- federal tax
  V1."FederalTaxNumber",
  V2."FederalTaxNumber" AS "ConFederalTaxNumber",
  -- provider patient
  V1."P_PatientID",
  V1."P_AppPatientID",
  V1."P_PAdmissionID",
  V1."P_PName",
  V1."P_PFName",
  V1."P_PLName",
  V1."P_PMedicaidNumber",
  V1."P_PStatus",
  V1."P_PAddressID",
  V1."P_PAppAddressID",
  V1."P_PAddressL1",
  V1."P_PAddressL2",
  V1."P_PCity",
  V1."P_PAddressState",
  V1."P_PZipCode",
  V1."P_PCounty",
  -- conflict provider patient
  V2."P_PatientID"    AS "ConP_PatientID",
  V2."P_AppPatientID" AS "ConP_AppPatientID",
  V2."P_PAdmissionID" AS "ConP_PAdmissionID",
  V2."P_PName"        AS "ConP_PName",
  V2."P_PFName"       AS "ConP_PFName",
  V2."P_PLName"       AS "ConP_PLName",
  V2."P_PMedicaidNumber" AS "ConP_PMedicaidNumber",
  V2."P_PStatus"      AS "ConP_PStatus",
  V2."P_PAddressID"   AS "ConP_PAddressID",
  V2."P_PAppAddressID" AS "ConP_PAppAddressID",
  V2."P_PAddressL1"   AS "ConP_PAddressL1",
  V2."P_PAddressL2"   AS "ConP_PAddressL2",
  V2."P_PCity"        AS "ConP_PCity",
  V2."P_PAddressState" AS "ConP_PAddressState",
  V2."P_PZipCode"     AS "ConP_PZipCode",
  V2."P_PCounty"      AS "ConP_PCounty",
  -- payer patient
  V1."PA_PatientID",
  V1."PA_AppPatientID",
  V1."PA_PAdmissionID",
  V1."PA_PName",
  V1."PA_PFName",
  V1."PA_PLName",
  V1."PA_PMedicaidNumber",
  V1."PA_PStatus",
  V1."PA_PAddressID",
  V1."PA_PAppAddressID",
  V1."PA_PAddressL1",
  V1."PA_PAddressL2",
  V1."PA_PCity",
  V1."PA_PAddressState",
  V1."PA_PZipCode",
  V1."PA_PCounty",
  -- conflict payer patient
  V2."PA_PatientID"    AS "ConPA_PatientID",
  V2."PA_AppPatientID" AS "ConPA_AppPatientID",
  V2."PA_PAdmissionID" AS "ConPA_PAdmissionID",
  V2."PA_PName"        AS "ConPA_PName",
  V2."PA_PFName"       AS "ConPA_PFName",
  V2."PA_PLName"       AS "ConPA_PLName",
  V2."PA_PMedicaidNumber" AS "ConPA_PMedicaidNumber",
  V2."PA_PStatus"      AS "ConPA_PStatus",
  V2."PA_PAddressID"   AS "ConPA_PAddressID",
  V2."PA_PAppAddressID" AS "ConPA_PAppAddressID",
  V2."PA_PAddressL1"   AS "ConPA_PAddressL1",
  V2."PA_PAddressL2"   AS "ConPA_PAddressL2",
  V2."PA_PCity"        AS "ConPA_PCity",
  V2."PA_PAddressState" AS "ConPA_PAddressState",
  V2."PA_PZipCode"     AS "ConPA_PZipCode",
  V2."PA_PCounty"      AS "ConPA_PCounty",
  -- InService dates: V1=visit(NULL), V2=InService(actual)
  V1."InserviceStartDate",
  V1."InserviceEndDate",
  V2."InserviceStartDate" AS "ConInserviceStartDate",
  V2."InserviceEndDate"   AS "ConInserviceEndDate"
FROM
  inservice_visits V1
  INNER JOIN inservice_events V2
    ON V1."SSN" = V2."SSN"
    AND V1."ProviderID" != V2."ProviderID"
    AND V1."ProviderID" IS NOT NULL
    AND V1."AppProviderID" IS NOT NULL
    AND CAST(V1."VisitStartTime" AS TIMESTAMP) <= CAST(V2."InserviceEndDate" AS TIMESTAMP)
    AND CAST(V1."VisitEndTime" AS TIMESTAMP)   >= CAST(V2."InserviceStartDate" AS TIMESTAMP)

UNION ALL

-- ──────────────────────────────────────────────────────────────────────────
-- Direction 2: InService event (primary) vs Visit (conflicting)
-- ──────────────────────────────────────────────────────────────────────────
SELECT
  DISTINCT
  -- identifiers
  CAST(NULL AS STRING) AS "CONFLICTID",
  V1."SSN",
  -- visit 1 (primary = InService event)
  V1."ProviderID",
  V1."AppProviderID",
  V1."ProviderName",
  V1."VisitID",
  V1."AppVisitID",
  -- visit 2 (conflicting = regular visit)
  V2."ProviderID"  AS "ConProviderID",
  V2."AppProviderID" AS "ConAppProviderID",
  V2."ProviderName"  AS "ConProviderName",
  V2."VisitID"      AS "ConVisitID",
  V2."AppVisitID"   AS "ConAppVisitID",
  -- dates / times
  V1."VisitDate",
  V1."SchStartTime",
  V1."SchEndTime",
  V2."SchStartTime"  AS "ConSchStartTime",
  V2."SchEndTime"    AS "ConSchEndTime",
  V1."VisitStartTime",
  V1."VisitEndTime",
  V2."VisitStartTime" AS "ConVisitStartTime",
  V2."VisitEndTime"   AS "ConVisitEndTime",
  V1."EVVStartTime",
  V1."EVVEndTime",
  V2."EVVStartTime"  AS "ConEVVStartTime",
  V2."EVVEndTime"    AS "ConEVVEndTime",
  -- caregiver
  V1."CaregiverID",
  V1."AppCaregiverID",
  V1."AideCode",
  V1."AideName",
  V1."AideFName",
  V1."AideLName",
  V1."AideSSN",
  V1."AideStatus",
  V2."CaregiverID"  AS "ConCaregiverID",
  V2."AppCaregiverID" AS "ConAppCaregiverID",
  V2."AideCode"     AS "ConAideCode",
  V2."AideName"     AS "ConAideName",
  V2."AideFName"    AS "ConAideFName",
  V2."AideLName"    AS "ConAideLName",
  V2."AideSSN"      AS "ConAideSSN",
  V2."AideStatus"   AS "ConAideStatus",
  -- office
  V1."OfficeID",
  V1."AppOfficeID",
  V1."Office",
  V2."OfficeID"    AS "ConOfficeID",
  V2."AppOfficeID" AS "ConAppOfficeID",
  V2."Office"      AS "ConOffice",
  -- patient
  V1."PatientID",
  V1."AppPatientID",
  V1."PAdmissionID",
  V1."PName",
  V1."PFName",
  V1."PLName",
  V1."PMedicaidNumber",
  V1."PStatus",
  V1."PAddressID",
  V1."PAppAddressID",
  V1."PAddressL1",
  V1."PAddressL2",
  V1."PCity",
  V1."PAddressState",
  V1."PZipCode",
  V1."PCounty",
  V1."Longitude" AS "PLongitude",
  V1."Latitude"  AS "PLatitude",
  -- conflict patient
  V2."PatientID"    AS "ConPatientID",
  V2."AppPatientID" AS "ConAppPatientID",
  V2."PAdmissionID" AS "ConPAdmissionID",
  V2."PName"        AS "ConPName",
  V2."PFName"       AS "ConPFName",
  V2."PLName"       AS "ConPLName",
  V2."PMedicaidNumber" AS "ConPMedicaidNumber",
  V2."PStatus"      AS "ConPStatus",
  V2."PAddressID"   AS "ConPAddressID",
  V2."PAppAddressID" AS "ConPAppAddressID",
  V2."PAddressL1"   AS "ConPAddressL1",
  V2."PAddressL2"   AS "ConPAddressL2",
  V2."PCity"        AS "ConPCity",
  V2."PAddressState" AS "ConPAddressState",
  V2."PZipCode"     AS "ConPZipCode",
  V2."PCounty"      AS "ConPCounty",
  V2."Longitude"    AS "ConPLongitude",
  V2."Latitude"     AS "ConPLatitude",
  -- payer
  V1."PayerID",
  V1."AppPayerID",
  V1."Contract",
  V1."PayerState",
  V2."PayerID"    AS "ConPayerID",
  V2."AppPayerID" AS "ConAppPayerID",
  V2."Contract"   AS "ConContract",
  V2."PayerState" AS "ConPayerState",
  -- billing
  V1."BilledDate",
  V2."BilledDate"    AS "ConBilledDate",
  V1."BilledHours",
  V2."BilledHours"   AS "ConBilledHours",
  V1."Billed",
  V2."Billed"        AS "ConBilled",
  V1."BilledRate",
  V1."TotalBilledAmount",
  V1."BillRateNonBilled",
  V1."BillRateBoth",
  V2."BilledRate"         AS "ConBilledRate",
  V2."TotalBilledAmount"  AS "ConTotalBilledAmount",
  V2."BillRateNonBilled"  AS "ConBillRateNonBilled",
  V2."BillRateBoth"       AS "ConBillRateBoth",
  -- distance / travel: always NULL for InService conflicts
  CAST(NULL AS NUMBER) AS "MinuteDiffBetweenSch",
  CAST(NULL AS NUMBER) AS "DistanceMilesFromLatLng",
  CAST(NULL AS NUMBER) AS "AverageMilesPerHour",
  CAST(NULL AS NUMBER) AS "ETATravleMinutes",
  -- service code
  V1."ServiceCodeID",
  V1."AppServiceCodeID",
  V1."RateType",
  V1."ServiceCode",
  V2."ServiceCodeID"    AS "ConServiceCodeID",
  V2."AppServiceCodeID" AS "ConAppServiceCodeID",
  V2."RateType"         AS "ConRateType",
  V2."ServiceCode"      AS "ConServiceCode",
  -- conflict flags: all 'N' for InService
  'N' AS "SameSchTimeFlag",
  'N' AS "SameVisitTimeFlag",
  'N' AS "SchAndVisitTimeSameFlag",
  'N' AS "SchOverAnotherSchTimeFlag",
  'N' AS "VisitTimeOverAnotherVisitTimeFlag",
  'N' AS "SchTimeOverVisitTimeFlag",
  'N' AS "DistanceFlag",
  -- missed / EVV
  V1."IsMissed",
  V1."MissedVisitReason",
  V1."EVVType",
  V2."IsMissed"         AS "ConIsMissed",
  V2."MissedVisitReason" AS "ConMissedVisitReason",
  V2."EVVType"          AS "ConEVVType",
  -- agency contact
  V1."AgencyContact",
  V2."AgencyContact"  AS "ConAgencyContact",
  V1."AgencyPhone",
  V2."AgencyPhone"    AS "ConAgencyPhone",
  -- last updated
  V1."LastUpdatedBy",
  V2."LastUpdatedBy"   AS "ConLastUpdatedBy",
  V1."LastUpdatedDate",
  V2."LastUpdatedDate" AS "ConLastUpdatedDate",
  -- contract type
  V1."ContractType",
  V2."ContractType"  AS "ConContractType",
  -- federal tax
  V1."FederalTaxNumber",
  V2."FederalTaxNumber" AS "ConFederalTaxNumber",
  -- provider patient
  V1."P_PatientID",
  V1."P_AppPatientID",
  V1."P_PAdmissionID",
  V1."P_PName",
  V1."P_PFName",
  V1."P_PLName",
  V1."P_PMedicaidNumber",
  V1."P_PStatus",
  V1."P_PAddressID",
  V1."P_PAppAddressID",
  V1."P_PAddressL1",
  V1."P_PAddressL2",
  V1."P_PCity",
  V1."P_PAddressState",
  V1."P_PZipCode",
  V1."P_PCounty",
  -- conflict provider patient
  V2."P_PatientID"    AS "ConP_PatientID",
  V2."P_AppPatientID" AS "ConP_AppPatientID",
  V2."P_PAdmissionID" AS "ConP_PAdmissionID",
  V2."P_PName"        AS "ConP_PName",
  V2."P_PFName"       AS "ConP_PFName",
  V2."P_PLName"       AS "ConP_PLName",
  V2."P_PMedicaidNumber" AS "ConP_PMedicaidNumber",
  V2."P_PStatus"      AS "ConP_PStatus",
  V2."P_PAddressID"   AS "ConP_PAddressID",
  V2."P_PAppAddressID" AS "ConP_PAppAddressID",
  V2."P_PAddressL1"   AS "ConP_PAddressL1",
  V2."P_PAddressL2"   AS "ConP_PAddressL2",
  V2."P_PCity"        AS "ConP_PCity",
  V2."P_PAddressState" AS "ConP_PAddressState",
  V2."P_PZipCode"     AS "ConP_PZipCode",
  V2."P_PCounty"      AS "ConP_PCounty",
  -- payer patient
  V1."PA_PatientID",
  V1."PA_AppPatientID",
  V1."PA_PAdmissionID",
  V1."PA_PName",
  V1."PA_PFName",
  V1."PA_PLName",
  V1."PA_PMedicaidNumber",
  V1."PA_PStatus",
  V1."PA_PAddressID",
  V1."PA_PAppAddressID",
  V1."PA_PAddressL1",
  V1."PA_PAddressL2",
  V1."PA_PCity",
  V1."PA_PAddressState",
  V1."PA_PZipCode",
  V1."PA_PCounty",
  -- conflict payer patient
  V2."PA_PatientID"    AS "ConPA_PatientID",
  V2."PA_AppPatientID" AS "ConPA_AppPatientID",
  V2."PA_PAdmissionID" AS "ConPA_PAdmissionID",
  V2."PA_PName"        AS "ConPA_PName",
  V2."PA_PFName"       AS "ConPA_PFName",
  V2."PA_PLName"       AS "ConPA_PLName",
  V2."PA_PMedicaidNumber" AS "ConPA_PMedicaidNumber",
  V2."PA_PStatus"      AS "ConPA_PStatus",
  V2."PA_PAddressID"   AS "ConPA_PAddressID",
  V2."PA_PAppAddressID" AS "ConPA_PAppAddressID",
  V2."PA_PAddressL1"   AS "ConPA_PAddressL1",
  V2."PA_PAddressL2"   AS "ConPA_PAddressL2",
  V2."PA_PCity"        AS "ConPA_PCity",
  V2."PA_PAddressState" AS "ConPA_PAddressState",
  V2."PA_PZipCode"     AS "ConPA_PZipCode",
  V2."PA_PCounty"      AS "ConPA_PCounty",
  -- InService dates: V1=InService(actual), V2=visit(NULL)
  V1."InserviceStartDate",
  V1."InserviceEndDate",
  V2."InserviceStartDate" AS "ConInserviceStartDate",
  V2."InserviceEndDate"   AS "ConInserviceEndDate"
FROM
  inservice_events V1
  INNER JOIN inservice_visits V2
    ON V1."SSN" = V2."SSN"
    AND V1."ProviderID" != V2."ProviderID"
    AND V2."ProviderID" IS NOT NULL
    AND V2."AppProviderID" IS NOT NULL
    AND CAST(V2."VisitStartTime" AS TIMESTAMP) <= CAST(V1."InserviceEndDate" AS TIMESTAMP)
    AND CAST(V2."VisitEndTime" AS TIMESTAMP)   >= CAST(V1."InserviceStartDate" AS TIMESTAMP);
